### ISSUE TITLE
Migration failed

### ISSUE THREAD

**Issue by SirMartin** [IgnisDa/ryot#1058]
Hi,

I am getting this errors while applying the migration scripts to update to the latest version, I followed the instructions in the documentation, I have 2 instances, and failed on both.

I was on the 6.7.6 version, I updated to 6.11.0 and everything worked fine, and after updated to 7.5.0 and got this error:

I have only a backup for version 6.7.6

```
[backend] 2024-10-07T08:11:01.108815Z  INFO sea_orm_migration::migrator: Migration 'm20240831_add_templates_key_to_preferences' has been applied
[backend] 2024-10-07T08:11:01.109523Z  INFO sea_orm_migration::migrator: Applying migration 'm20240831_add_is_account_default_column_to_access_link'
[backend] 2024-10-07T08:11:01.112460Z ERROR ryot: Database migration failed: Execution Error: error returned from database: relation "access_link" does not exist
[backend] Error: There was an error running the database migrations.
```

**Comment by SirMartin** [comment]
It would be nice if you can give me the exact command you use to restore the DB backup, because I am trying and cannot make it work

**Comment by IgnisDa** [comment]
```
export PGHOST=localhost PGDATABASE=postgres PGPASSWORD=post
gres PGUSER=postgres && dropdb $PGDATABASE --force && createdb $$PGDATABASE && pg_restore --verbose -d $PGDATABASE < tmp/file.sql # my db
```

You may need to expose your database to 5432 change the values.

Also please send me a dump of your database so that I can take a look at what is wrong.

**Comment by SirMartin** [comment]
I sent this morning.

**Comment by IgnisDa** [comment]
yes i have recieved it. if possible, pls join thr ryot discord in case i need anything else from you.

**Comment by SirMartin** [comment]
Finally I could restore the dump you sent to me, but when I try to log in, it crashes.

![image](https://github.com/user-attachments/assets/888485ac-5de4-4a29-9b4a-60789a736861)

This is the response of the endpoint `auth.data?intent=login`

`[{"_1":2},"error",["SanitizedError",3,4,-7],"Error","Unexpected Server Error"]`

And that are the logs in the container.

```
[frontend] }

[frontend] POST /auth.data?intent=login 500 - - 16.760 ms

[frontend] GET /auth?intent=login 200 - - 24.165 ms

[backend] thread 'tokio-runtime-worker' panicked at /home/runner/work/ryot/ryot/crates/services/user/src/lib.rs:355:63:

[backend] called `Result::unwrap()` on an `Err` value: Query(SqlxError(ColumnDecode { index: "\"preferences\"", source: Error("invalid type: string \"Netflix\", expected struct UserGeneralWatchProvider", line: 1, column: 1338) }))

[frontend] ClientError: GraphQL Error (Code: 500): {"response":{"status":500,"headers":{}},"request":{"query":"mutation LoginUser($input: AuthUserInput!) {\n  loginUser(input: $input) {\n    __typename\n    ... on LoginError {\n      error\n    }\n    ... on LoginResponse {\n      apiKey\n    }\n  }\n}","variables":{"input":{"password":{"password":"bcb_uat2CYE_uvd4pjx","username":"edu"}}}}}

[frontend]     at runRequest (file:///home/ryot/node_modules/graphql-request/src/legacy/helpers/runRequest.ts:75:12)

[frontend]     at processTicksAndRejections (node:internal/process/task_queues:95:5)

[frontend]     at AuthenticatedGraphQLClient.request (file:///home/ryot/node_modules/graphql-request/src/legacy/classes/GraphQLClient.ts:131:22)

[frontend]     at Object.login (file:///home/ryot/build/server/index.js?t=1728349809000:16534:29)

[frontend]     at Object.callRouteAction (/home/ryot/node_modules/@remix-run/server-runtime/dist/data.js:36:16)

[frontend]     at /home/ryot/node_modules/@remix-run/server-runtime/dist/single-fetch.js:47:84

[frontend]     at callLoaderOrAction (/home/ryot/node_modules/@remix-run/router/router.ts:4891:16)

[frontend]     at /home/ryot/node_modules/@remix-run/server-runtime/dist/single-fetch.js:45:20

[frontend]     at async Promise.all (index 1)

[frontend]     at /home/ryot/node_modules/@remix-run/server-runtime/dist/single-fetch.js:44:19 {

[frontend]   response: {

[frontend]     status: 500,

[frontend]     headers: Headers {

[frontend]       'access-control-allow-credentials': 'true',

[frontend]       'content-length': '16',

[frontend]       'content-type': 'text/plain; charset=utf-8',

[frontend]       date: 'Thu, 10 Oct 2024 08:11:17 GMT',

[frontend]       server: 'Caddy',

[frontend]       vary: 'origin, access-control-request-method, access-control-request-headers'

[frontend]     }

[frontend]   },

[frontend]   request: {

[frontend]     query: 'mutation LoginUser($input: AuthUserInput!) {\n' +

[frontend]       '  loginUser(input: $input) {\n' +

[frontend]       '    __typename\n' +

[frontend]       '    ... on LoginError {\n' +

[frontend]       '      error\n' +

[frontend]       '    }\n' +

[frontend]       '    ... on LoginResponse {\n' +

[frontend]       '      apiKey\n' +

[frontend]       '    }\n' +

[frontend]       '  }\n' +

[frontend]       '}',

[frontend]     variables: { input: [Object] }

[frontend]   }


[frontend] }

[frontend] POST /auth.data?intent=login 500 - - 40.060 ms```
