### ISSUE TITLE
[Bug] Summary does not update upon progress change

### ISSUE THREAD

**Issue by Sazu-bit** [IgnisDa/ryot#244]
Possibly related #240 

On the front page it has a summary of your progress so far, chapters, episodes... but it also states 'last updated 53 years ago'. 

### What I expect to happen
When I update the progress of an anime/manga, the relevant summary area is updated accordingly.

### What actually happens
No change.

### Potential fix
No clue on this one.

**Comment by IgnisDa** [comment]
The summary calculation is a very expensive operation, so it happens once every 12 hrs. You can force one manually from the miscellaneous settings. You can also change the duration using `scheduler.user_cleanup_every` key (defaults to 12).

**Comment by Sazu-bit** [comment]
This is to say... since implementing and having a sleep it hasn't updated. I've waited 26hrs.

I have clicked each of the three options under Miscellaneous and... no change.

**Comment by IgnisDa** [comment]
Thats not right. Can you attach your logs? They should exactly update at 0:00 UTC and 12:00 UTC.

**Comment by Sazu-bit** [comment]
Terminal output since yesterday. Previous to this were just related to the migration.

```
2023-08-04T00:50:59.468169Z  INFO ryot: Listening on [::]:8000
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: ConnectionAcquire(Timeout)', apps/backend/src/miscellaneous/resolver.rs:3207:53
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'tokio-runtime-worker' panicked at 'internal error: entered unreachable code', apps/backend/src/miscellaneous/resolver.rs:2578:22
thread 'tokio-runtime-worker' panicked at 'internal error: entered unreachable code', apps/backend/src/miscellaneous/resolver.rs:2578:22
thread 'tokio-runtime-worker' panicked at 'internal error: entered unreachable code', apps/backend/src/miscellaneous/resolver.rs:2573:22
thread 'tokio-runtime-worker' panicked at 'internal error: entered unreachable code', apps/backend/src/miscellaneous/resolver.rs:2578:22
thread 'tokio-runtime-worker' panicked at 'internal error: entered unreachable code', apps/backend/src/miscellaneous/resolver.rs:2578:22
thread 'tokio-runtime-worker' panicked at 'internal error: entered unreachable code', apps/backend/src/miscellaneous/resolver.rs:2573:22
thread 'tokio-runtime-worker' panicked at 'internal error: entered unreachable code', apps/backend/src/miscellaneous/resolver.rs:2578:22
thread 'tokio-runtime-worker' panicked at 'internal error: entered unreachable code', apps/backend/src/miscellaneous/resolver.rs:2578:22
thread 'tokio-runtime-worker' panicked at 'internal error: entered unreachable code', apps/backend/src/miscellaneous/resolver.rs:2578:22
thread 'tokio-runtime-worker' panicked at 'internal error: entered unreachable code', apps/backend/src/miscellaneous/resolver.rs:2573:22
thread 'tokio-runtime-worker' panicked at 'internal error: entered unreachable code', apps/backend/src/miscellaneous/resolver.rs:2578:22
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Exec(SqlxError(Database(SqliteError { code: 2067, message: "UNIQUE constraint failed: genre.name" })))', apps/backend/src/miscellaneous/resolver.rs:2279:38
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: ConnectionAcquire(Timeout)', apps/backend/src/miscellaneous/resolver.rs:3207:53
thread 'tokio-runtime-worker' panicked at 'internal error: entered unreachable code', apps/backend/src/miscellaneous/resolver.rs:2578:22
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: ConnectionAcquire(Timeout)', apps/backend/src/miscellaneous/resolver.rs:2066:18
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: ConnectionAcquire(Timeout)', apps/backend/src/miscellaneous/resolver.rs:2331:18
thread 'tokio-runtime-worker' panicked at 'internal error: entered unreachable code', apps/backend/src/miscellaneous/resolver.rs:2578:22
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: ConnectionAcquire(Timeout)', apps/backend/src/miscellaneous/resolver.rs:3207:53
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: ConnectionAcquire(Timeout)', apps/backend/src/miscellaneous/resolver.rs:2271:14
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: ConnectionAcquire(Timeout)', apps/backend/src/miscellaneous/resolver.rs:3207:53
```

**Comment by IgnisDa** [comment]
Are you using Sqlite?

**Comment by Sazu-bit** [comment]
I honestly have not a clue. I just followed the installation instructions as closely as possible and bam. It didn't mention anything about installing a database.

**Comment by IgnisDa** [comment]
The logs will mention the database.

**Comment by IgnisDa** [comment]
![image](https://github.com/IgnisDa/ryot/assets/60938164/e908f3be-e996-40ea-bbbe-65506133e81e)

**Comment by Sazu-bit** [comment]
Ah yes, it's running SQLite

**Comment by Sazu-bit** [comment]
```
2023-08-04T00:50:56.249999Z  INFO ryot: Running version 2.0.3
2023-08-04T00:50:56.301564Z  INFO ryot: Using database backend: "SQLite"
2023-08-04T00:50:56.489490Z  INFO sea_orm_migration::migrator: Applying all pending migrations
```

**Comment by IgnisDa** [comment]
Can you switch to Postgres?

**Comment by IgnisDa** [comment]
I have tried to fix this problem for Sqlite for a long time, but havent figured out a solution

**Comment by Sazu-bit** [comment]
I'm going to close this as currently unresolvable then. The reason I'm closing is that I don't have the time to contribute to software I'm not going to be using. See issue #240 https://github.com/IgnisDa/ryot/issues/240#issuecomment-1666568257 .
