### ISSUE TITLE
Importing from mediatracker not working

### ISSUE THREAD

**Issue by flavorgold1** [IgnisDa/ryot#258]
```
2023-08-11T14:55:08.862988Z  INFO ryot: Running version 2.5.0
2023-08-11T14:55:08.880591Z  INFO ryot: Using database backend: "PostgreSQL"
2023-08-11T14:55:08.881468Z  INFO sea_orm_migration::migrator: Applying all pending migrations
2023-08-11T14:55:08.883145Z  INFO sea_orm_migration::migrator: No pending migrations
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: failed to lookup address information: Try again', apps/backend/src/providers/listennotes.rs:242:54
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
2023-08-11T14:55:14.415494Z  INFO ryot: Running version 2.5.0
2023-08-11T14:55:14.431633Z  INFO ryot: Using database backend: "PostgreSQL"
2023-08-11T14:55:14.432421Z  INFO sea_orm_migration::migrator: Applying all pending migrations
2023-08-11T14:55:14.433786Z  INFO sea_orm_migration::migrator: No pending migrations
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: failed to lookup address information: Try again', apps/backend/src/providers/tmdb.rs:605:61
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
2023-08-11T14:55:19.932024Z  INFO ryot: Running version 2.5.0
2023-08-11T14:55:19.950566Z  INFO ryot: Using database backend: "PostgreSQL"
2023-08-11T14:55:19.951256Z  INFO sea_orm_migration::migrator: Applying all pending migrations
2023-08-11T14:55:19.952534Z  INFO sea_orm_migration::migrator: No pending migrations
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: failed to lookup address information: Try again', apps/backend/src/providers/tmdb.rs:605:61
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
2023-08-11T14:55:25.635516Z  INFO ryot: Running version 2.5.0
2023-08-11T14:55:25.651859Z  INFO ryot: Using database backend: "PostgreSQL"
2023-08-11T14:55:25.652628Z  INFO sea_orm_migration::migrator: Applying all pending migrations
2023-08-11T14:55:25.653919Z  INFO sea_orm_migration::migrator: No pending migrations
2023-08-11T14:55:34.254607Z  INFO ryot: Listening on [::]:8793
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: RelativeUrlWithoutBase', apps/backend/src/importer/media_tracker.rs:145:70
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

What's going on here?

**Comment by flavorgold1** [comment]
> What input are you using?

What do you mean? I don't understand your question.

Sorry. That output above was from `sudo docker logs ryot`.

**Comment by IgnisDa** [comment]
When you deploy the import, what Url are you putting in the input? I think you're putting the wrong value.

**Comment by flavorgold1** [comment]
It's in the `https://x.y.net` format, and accessible.

1 show transferred in but that was it, after waiting for hours.

**Comment by IgnisDa** [comment]
Can you set `RUST_LOG=Ryot=trace` environment variable and try again?

**Comment by IgnisDa** [comment]
Closing due to inactivity. Feel free to re-open.
