### ISSUE TITLE
error after update: Sqlite doesn't support multiple alter options

### ISSUE THREAD

**Issue by LnLcFlx** [IgnisDa/ryot#370]
After updating from v2.18.8 to v2.19.0 I get an error related to SQLite.

```
INFO ryot: Running version 2.19.0
INFO ryot: Using database backend: "SQLite"
INFO sea_orm_migration::migrator: Applying all pending migrations
INFO sea_orm_migration::migrator: Applying migration 'm20230927_add_person_id_field_to_review'
thread 'main' panicked at 'Sqlite doesn't support multiple alter options', /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/sea-query-0.30.1/src/backend/sqlite/table.rs:119:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by LnLcFlx** [comment]
My mistake. Forgot to read the migration notes.

**Comment by LnLcFlx** [comment]
My mistake again...
I set the environment variables as explained but the issue persists and Ryot won't start.

**Comment by IgnisDa** [comment]
Hey! Any particular reason for using sqlite? I plan to drop support for it soon.

**Comment by IgnisDa** [comment]
That being said, what was the last version that was running for you?

**Comment by LnLcFlx** [comment]
I just wanted to test ryot so I though sqlite will do fine. But now I intend on using it permanently and am stuck with sqlite.

Never migrated from sqlite to postgres before. Do you have a recommended method by chance?

**Comment by IgnisDa** [comment]
You can use the guide at https://ignisda.github.io/ryot/guides/exporting.html to export then https://ignisda.github.io/ryot/importing.html#media-json to import it back. Though I would suggest you do a test run and see how many get imported.

**Comment by LnLcFlx** [comment]
Now I get
```
INFO ryot: Running version 2.19.2
INFO ryot: Using database backend: "SQLite"
INFO sea_orm_migration::migrator: Applying all pending migrations
INFO sea_orm_migration::migrator: Applying migration 'm20230927_add_person_id_field_to_review'
INFO sea_orm_migration::migrator: Migration 'm20230927_add_person_id_field_to_review' has been applied
INFO sea_orm_migration::migrator: Applying migration 'm20230927_change_faulty_index_person_table'
Error: Execution Error: error returned from database: (code: 1) index person-identifier-source__unique_index already exists


Caused by:
    error returned from database: (code: 1) index person-identifier-source__unique_index already exists
```
And on the second starting attempt:
```
INFO ryot: Running version 2.19.2
INFO ryot: Using database backend: "SQLite"
INFO sea_orm_migration::migrator: Applying all pending migrations
INFO sea_orm_migration::migrator: Applying migration 'm20230927_change_faulty_index_person_table'
Error: Execution Error: error returned from database: (code: 1) no such index: person-identifier-source__unique_index


Caused by:
    error returned from database: (code: 1) no such index: person-identifier-source__unique_index
```
:/

**Comment by IgnisDa** [comment]
Can you run it with `RUST_LOG=sea-orm=trace` env variable?

**Comment by LnLcFlx** [comment]
> Can you run it with `RUST_LOG=sea_orm=trace` env variable?

Is this correct? Then it only prints
```
Error: Execution Error: error returned from database: (code: 1) no such index: person-identifier-source__unique_index


Caused by:
    error returned from database: (code: 1) no such index: person-identifier-source__unique_index
```
without the INFO parts

**Comment by LnLcFlx** [comment]
Ah you changed `-` to `_`.

```
DEBUG execute{self=SqlxSqlitePoolConnection stmt=Statement { sql: "CREATE TABLE IF NOT EXISTS \"seaql_migrations\" ( \"version\" text NOT NULL PRIMARY KEY, \"applied_at\" bigint NOT NULL )", values: None, db_backend: Sqlite }}:execute{self=SqlxSqlitePoolConnection { pool: Pool { size: 5, num_idle: 5, is_closed: false, options: PoolOptions { max_connections: 10, min_connections: 5, connect_timeout: 10s, max_lifetime: Some(1800s), idle_timeout: Some(600s), test_before_acquire: true } } } stmt=Statement { sql: "CREATE TABLE IF NOT EXISTS \"seaql_migrations\" ( \"version\" text NOT NULL PRIMARY KEY, \"applied_at\" bigint NOT NULL )", values: None, db_backend: Sqlite }}: sea_orm::driver::sqlx_sqlite: CREATE TABLE IF NOT EXISTS "seaql_migrations" ( "version" text NOT NULL PRIMARY KEY, "applied_at" bigint NOT NULL )
 INFO sea_orm_migration::migrator: Applying all pending migrations
DEBUG execute{self=SqlxSqlitePoolConnection stmt=Statement { sql: "CREATE TABLE IF NOT EXISTS \"seaql_migrations\" ( \"version\" text NOT NULL PRIMARY KEY, \"applied_at\" bigint NOT NULL )", values: None, db_backend: Sqlite }}:execute{self=SqlxSqlitePoolConnection { pool: Pool { size: 5, num_idle: 5, is_closed: false, options: PoolOptions { max_connections: 10, min_connections: 5, connect_timeout: 10s, max_lifetime: Some(1800s), idle_timeout: Some(600s), test_before_acquire: true } } } stmt=Statement { sql: "CREATE TABLE IF NOT EXISTS \"seaql_migrations\" ( \"version\" text NOT NULL PRIMARY KEY, \"applied_at\" bigint NOT NULL )", values: None, db_backend: Sqlite }}: sea_orm::driver::sqlx_sqlite: CREATE TABLE IF NOT EXISTS "seaql_migrations" ( "version" text NOT NULL PRIMARY KEY, "applied_at" bigint NOT NULL )
DEBUG execute{self=SqlxSqlitePoolConnection stmt=Statement { sql: "CREATE TABLE IF NOT EXISTS \"seaql_migrations\" ( \"version\" text NOT NULL PRIMARY KEY, \"applied_at\" bigint NOT NULL )", values: None, db_backend: Sqlite }}:execute{self=SqlxSqlitePoolConnection { pool: Pool { size: 5, num_idle: 5, is_closed: false, options: PoolOptions { max_connections: 10, min_connections: 5, connect_timeout: 10s, max_lifetime: Some(1800s), idle_timeout: Some(600s), test_before_acquire: true } } } stmt=Statement { sql: "CREATE TABLE IF NOT EXISTS \"seaql_migrations\" ( \"version\" text NOT NULL PRIMARY KEY, \"applied_at\" bigint NOT NULL )", values: None, db_backend: Sqlite }}: sea_orm::driver::sqlx_sqlite: CREATE TABLE IF NOT EXISTS "seaql_migrations" ( "version" text NOT NULL PRIMARY KEY, "applied_at" bigint NOT NULL )
DEBUG execute{self=SqlxSqlitePoolConnection stmt=Statement { sql: "CREATE TABLE IF NOT EXISTS \"seaql_migrations\" ( \"version\" text NOT NULL PRIMARY KEY, \"applied_at\" bigint NOT NULL )", values: None, db_backend: Sqlite }}:execute{self=SqlxSqlitePoolConnection { pool: Pool { size: 5, num_idle: 5, is_closed: false, options: PoolOptions { max_connections: 10, min_connections: 5, connect_timeout: 10s, max_lifetime: Some(1800s), idle_timeout: Some(600s), test_before_acquire: true } } } stmt=Statement { sql: "CREATE TABLE IF NOT EXISTS \"seaql_migrations\" ( \"version\" text NOT NULL PRIMARY KEY, \"applied_at\" bigint NOT NULL )", values: None, db_backend: Sqlite }}: sea_orm::driver::sqlx_sqlite: CREATE TABLE IF NOT EXISTS "seaql_migrations" ( "version" text NOT NULL PRIMARY KEY, "applied_at" bigint NOT NULL )
DEBUG query_all{self=SqlxSqlitePoolConnection stmt=Statement { sql: "SELECT \"version\", \"applied_at\" FROM \"seaql_migrations\" ORDER BY \"version\" ASC", values: Some(Values([])), db_backend: Sqlite }}:query_all{self=SqlxSqlitePoolConnection { pool: Pool { size: 5, num_idle: 5, is_closed: false, options: PoolOptions { max_connections: 10, min_connections: 5, connect_timeout: 10s, max_lifetime: Some(1800s), idle_timeout: Some(600s), test_before_acquire: true } } } stmt=Statement { sql: "SELECT \"version\", \"applied_at\" FROM \"seaql_migrations\" ORDER BY \"version\" ASC", values: Some(Values([])), db_backend: Sqlite }}: sea_orm::driver::sqlx_sqlite: SELECT "version", "applied_at" FROM "seaql_migrations" ORDER BY "version" ASC
 INFO sea_orm_migration::migrator: Applying migration 'm20230927_change_faulty_index_person_table'
DEBUG execute{self=SqlxSqlitePoolConnection stmt=Statement { sql: "DROP INDEX \"person-identifier-source__unique_index\"", values: None, db_backend: Sqlite }}:execute{self=SqlxSqlitePoolConnection { pool: Pool { size: 5, num_idle: 5, is_closed: false, options: PoolOptions { max_connections: 10, min_connections: 5, connect_timeout: 10s, max_lifetime: Some(1800s), idle_timeout: Some(600s), test_before_acquire: true } } } stmt=Statement { sql: "DROP INDEX \"person-identifier-source__unique_index\"", values: None, db_backend: Sqlite }}: sea_orm::driver::sqlx_sqlite: DROP INDEX "person-identifier-source__unique_index"
Error: Execution Error: error returned from database: (code: 1) no such index: person-identifier-source__unique_index


Caused by:
    error returned from database: (code: 1) no such index: person-identifier-source__unique_index
```

**Comment by IgnisDa** [comment]
TBH I have no idea how to fix this. The drop index succeeds but then immediately recreating it doesn't?

Maybe downgrade to `v2.19.0` and then switch to postgres like I mentioned above.

**Comment by LnLcFlx** [comment]
Tried that and exported a Media json. But importing fails throwing a
```
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Error("invalid type: map, expected a sequence", line: 1, column: 0)', apps/backend/src/importer/media_json.rs:6:53
```
with no backtrace with `RUST_BACKTRACE=1`

**Comment by IgnisDa** [comment]
Can you share the JSON file you're trying to import? If you don't want to attach it here, you can email it to me. My email ID is in my GH profile.

**Comment by IgnisDa** [comment]
@LnLcFlx I checked your export. You have made an export for "all". Revisiting the exporting docs, you need to export just the "media" and then import it.

**Comment by LnLcFlx** [comment]
I still got a couple of the same lines in the logs
```
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Error { message: "missing field `id` at line 1 column 100", extensions: None }', apps/backend/src/background.rs:154:18
```
but the media seems to imported correctly now. Thanks!
I just have to manually change my settings.

**Comment by IgnisDa** [comment]
Yeah that error just means a person's data was not downloaded successfully. I'll see if I can make the errors better.

**Comment by kn-f** [comment]
@IgnisDa the issue is caused by the name of the index. Sqllite does not accept/allows dashes ( - ) in the name of the fields. If you change it with underscores, it should work.
That index is defined only in the "m20230413_create_person.rs" file, unfortunately I'm not able to understand the impact of changing the full impact of this change on the rest of the code and on the existing deployments.

FYI @LnLcFlx @tomcollis

**Comment by IgnisDa** [comment]
> Sqllite does not accept/allows dashes ( - ) in the name of the fields.

Could you guide me to the docs that say this?

**Comment by kn-f** [comment]
Unfortunately I could not find any official documentation. These are some articles indicating this limitation:
[StackOverflow](https://stackoverflow.com/questions/3694276/what-are-valid-table-names-in-sqlite)
[Blog](https://allinworld99.blogspot.com/2016/04/naming-standards-for-sqlite.html)

You can check this by running the query itself in sqlite:

> sqlite> create unique index person-identifier-source__unique_index on person (name);
> Error: near "-": syntax error
> sqlite> create unique index person_identifier_source__unique_index on person (name);
> sqlite> pragma index_list(person);
> 0|person_identifier_source__unique_index|1|c|0

**Comment by IgnisDa** [comment]
> Unfortunately I could not find any official documentation.

This is false.

![image](https://github.com/IgnisDa/ryot/assets/60938164/ffd89e75-095e-4f1c-a601-1205e3667106)

**Comment by IgnisDa** [comment]
And's Ryot migration process does generate the right SQL. You can set `RUST_LOG=sea_orm=trace` env variable and start  the server to see what SQL ryot is executing.

BTW, The original problem of this issue has been fixed in v3, ie, new Ryot instances should be able to use sqlite just fine.
