### ISSUE TITLE
Cannot add any media, error when clicking on any media tab

### ISSUE THREAD

**Issue by Forceu** [IgnisDa/ryot#46]
After running the container with `podman run --rm -p 8000:8000 ghcr.io/ignisda/ryot:latest`, I can register a new user and get to the main menu. When clicking on any tabs, I get the following error:

> Application error: a client-side exception has occurred (see the browser console for more information).

Adding volumes containing the configuration or data does not fix the issue.

```
framework-19f3649580393c10.js:9 TypeError: Cannot read properties of undefined (reading 'trim')
    at list-4ba8436c47a79ba7.js:1:9286
    at uI (framework-19f3649580393c10.js:9:84128)
    at oU (framework-19f3649580393c10.js:9:113199)
    at oC (framework-19f3649580393c10.js:9:96012)
    at r4 (framework-19f3649580393c10.js:9:44776)
    at framework-19f3649580393c10.js:9:111639
    at oI (framework-19f3649580393c10.js:9:111645)
    at oS (framework-19f3649580393c10.js:9:95015)
    at x (framework-19f3649580393c10.js:33:1373)
    at MessagePort.T (framework-19f3649580393c10.js:33:1903)
a5 @ framework-19f3649580393c10.js:9
main-54379c1fb512e6dc.js:1 TypeError: Cannot read properties of undefined (reading 'trim')
    at list-4ba8436c47a79ba7.js:1:9286
    at uI (framework-19f3649580393c10.js:9:84128)
    at oU (framework-19f3649580393c10.js:9:113199)
    at oC (framework-19f3649580393c10.js:9:96012)
    at r4 (framework-19f3649580393c10.js:9:44776)
    at framework-19f3649580393c10.js:9:111639
    at oI (framework-19f3649580393c10.js:9:111645)
    at oS (framework-19f3649580393c10.js:9:95015)
    at x (framework-19f3649580393c10.js:33:1373)
    at MessagePort.T (framework-19f3649580393c10.js:33:1903)
K @ main-54379c1fb512e6dc.js:1
main-54379c1fb512e6dc.js:1 A client-side exception has occurred, see here for more info: https://nextjs.org/docs/messages/client-side-exception-occurred
```

The console logs are as follow:

```
2023-05-25T13:52:02.758091Z  INFO ryot: Using database backend: "SQLite"
2023-05-25T13:52:02.758441Z  INFO sea_orm_migration::migrator: Applying all pending migrations
2023-05-25T13:52:02.758736Z  INFO sea_orm_migration::migrator: Applying migration 'm20230410_000001_create_metadata'
2023-05-25T13:52:02.759614Z  INFO sea_orm_migration::migrator: Migration 'm20230410_000001_create_metadata' has been applied
2023-05-25T13:52:02.759829Z  INFO sea_orm_migration::migrator: Applying migration 'm20230416_000002_create_creator'
2023-05-25T13:52:02.760484Z  INFO sea_orm_migration::migrator: Migration 'm20230416_000002_create_creator' has been applied
2023-05-25T13:52:02.760666Z  INFO sea_orm_migration::migrator: Applying migration 'm20230416_000003_create_book'
2023-05-25T13:52:02.760828Z  INFO sea_orm_migration::migrator: Migration 'm20230416_000003_create_book' has been applied
2023-05-25T13:52:02.761008Z  INFO sea_orm_migration::migrator: Applying migration 'm20230417_000004_create_user'
2023-05-25T13:52:02.761794Z  INFO sea_orm_migration::migrator: Migration 'm20230417_000004_create_user' has been applied
2023-05-25T13:52:02.761970Z  INFO sea_orm_migration::migrator: Applying migration 'm20230419_000005_create_seen'
2023-05-25T13:52:02.762161Z  INFO sea_orm_migration::migrator: Migration 'm20230419_000005_create_seen' has been applied
2023-05-25T13:52:02.762342Z  INFO sea_orm_migration::migrator: Applying migration 'm20230423_000006_create_movie'
2023-05-25T13:52:02.762501Z  INFO sea_orm_migration::migrator: Migration 'm20230423_000006_create_movie' has been applied
2023-05-25T13:52:02.762683Z  INFO sea_orm_migration::migrator: Applying migration 'm20230425_000007_create_show'
2023-05-25T13:52:02.762843Z  INFO sea_orm_migration::migrator: Migration 'm20230425_000007_create_show' has been applied
2023-05-25T13:52:02.763024Z  INFO sea_orm_migration::migrator: Applying migration 'm20230502_000008_create_video_game'
2023-05-25T13:52:02.763187Z  INFO sea_orm_migration::migrator: Migration 'm20230502_000008_create_video_game' has been applied
2023-05-25T13:52:02.763371Z  INFO sea_orm_migration::migrator: Applying migration 'm20230502_000009_create_genre'
2023-05-25T13:52:02.763832Z  INFO sea_orm_migration::migrator: Migration 'm20230502_000009_create_genre' has been applied
2023-05-25T13:52:02.764007Z  INFO sea_orm_migration::migrator: Applying migration 'm20230504_000010_create_summary'
2023-05-25T13:52:02.764160Z  INFO sea_orm_migration::migrator: Migration 'm20230504_000010_create_summary' has been applied
2023-05-25T13:52:02.764367Z  INFO sea_orm_migration::migrator: Applying migration 'm20230504_000011_create_audio_book'
2023-05-25T13:52:02.764545Z  INFO sea_orm_migration::migrator: Migration 'm20230504_000011_create_audio_book' has been applied
2023-05-25T13:52:02.764725Z  INFO sea_orm_migration::migrator: Applying migration 'm20230505_000012_create_review'
2023-05-25T13:52:02.764912Z  INFO sea_orm_migration::migrator: Migration 'm20230505_000012_create_review' has been applied
2023-05-25T13:52:02.765096Z  INFO sea_orm_migration::migrator: Applying migration 'm20230507_000013_create_collection'
2023-05-25T13:52:02.765748Z  INFO sea_orm_migration::migrator: Migration 'm20230507_000013_create_collection' has been applied
2023-05-25T13:52:02.765949Z  INFO sea_orm_migration::migrator: Applying migration 'm20230509_000014_create_media_import_report'
2023-05-25T13:52:02.766185Z  INFO sea_orm_migration::migrator: Migration 'm20230509_000014_create_media_import_report' has been applied
2023-05-25T13:52:02.766405Z  INFO sea_orm_migration::migrator: Applying migration 'm20230514_000015_create_podcast'
2023-05-25T13:52:02.766587Z  INFO sea_orm_migration::migrator: Migration 'm20230514_000015_create_podcast' has been applied
2023-05-25T13:52:03.172584Z  INFO ryot: Listening on 0.0.0.0:8000
2023-05-25T14:00:00.001744Z  INFO ryot::background: Cleaning up user and metadata association
2023-05-25T14:00:00.002153Z  INFO ryot::background: Removing old user summaries and regenerating them
2023-05-25T14:02:47.034850Z  INFO ryot::background: Running jobs after user creation
```

**Comment by IgnisDa** [comment]
Which browser and OS are you using? I noticed the same problem on Firefox Windows but not on Firefox Linux.

**Comment by Forceu** [comment]
Chrome 113.0.5672.126 on Ubuntu 22.04.

The same occurs with Firefox, but with a different output:


```
Unexpected value 1.2rem parsing width attribute. [list](http://localhost:8000/list?lot=book)
Unexpected value 1.2rem parsing height attribute. [list](http://localhost:8000/list?lot=book)
Unexpected value 1.2rem parsing width attribute. [list](http://localhost:8000/list?lot=book)
Unexpected value 1.2rem parsing height attribute. [list](http://localhost:8000/list?lot=book)
Unexpected value 1.2rem parsing width attribute. [list](http://localhost:8000/list?lot=book)
Unexpected value 1.2rem parsing height attribute. [list](http://localhost:8000/list?lot=book)
Unexpected value 1.2rem parsing width attribute. [list](http://localhost:8000/list?lot=book)
Unexpected value 1.2rem parsing height attribute. [list](http://localhost:8000/list?lot=book)
TypeError: F is undefined
    NextJS 29
[framework-19f3649580393c10.js:9:69814](http://localhost:8000/_next/static/chunks/framework-19f3649580393c10.js)
TypeError: F is undefined
    NextJS 29
[main-54379c1fb512e6dc.js:1:10107](http://localhost:8000/_next/static/chunks/main-54379c1fb512e6dc.js)
A client-side exception has occurred, see here for more info: https://nextjs.org/docs/messages/client-side-exception-occurred [main-54379c1fb512e6dc.js:1:10124](http://localhost:8000/_next/static/chunks/main-54379c1fb512e6dc.js)
Unexpected value 1.2rem parsing width attribute. [framework-19f3649580393c10.js:9:3251](http://localhost:8000/_next/static/chunks/framework-19f3649580393c10.js)
Unexpected value 1.2rem parsing height attribute. [framework-19f3649580393c10.js:9:3251](http://localhost:8000/_next/static/chunks/framework-19f3649580393c10.js)
Unexpected value 1.2rem parsing width attribute. [framework-19f3649580393c10.js:9:3251](http://localhost:8000/_next/static/chunks/framework-19f3649580393c10.js)
Unexpected value 1.2rem parsing height attribute. [framework-19f3649580393c10.js:9:3251](http://localhost:8000/_next/static/chunks/framework-19f3649580393c10.js)
Unexpected value 1.2rem parsing width attribute. [framework-19f3649580393c10.js:9:3251](http://localhost:8000/_next/static/chunks/framework-19f3649580393c10.js)
Unexpected value 1.2rem parsing height attribute. [framework-19f3649580393c10.js:9:3251](http://localhost:8000/_next/static/chunks/framework-19f3649580393c10.js)
Unexpected value 1.2rem parsing width attribute. [framework-19f3649580393c10.js:9:3251](http://localhost:8000/_next/static/chunks/framework-19f3649580393c10.js)
Unexpected value 1.2rem parsing height attribute. [framework-19f3649580393c10.js:9:3251](http://localhost:8000/_next/static/chunks/framework-19f3649580393c10.js)
Unexpected value 1.5rem parsing width attribute. [framework-19f3649580393c10.js:9:3251](http://localhost:8000/_next/static/chunks/framework-19f3649580393c10.js)
Unexpected value 1.5rem parsing height attribute. [framework-19f3649580393c10.js:9:3251](http://localhost:8000/_next/static/chunks/framework-19f3649580393c10.js)
Unexpected value 1.5rem parsing width attribute. [framework-19f3649580393c10.js:9:3251](http://localhost:8000/_next/static/chunks/framework-19f3649580393c10.js)
Unexpected value 1.5rem parsing height attribute. [framework-19f3649580393c10.js:9:3251](http://localhost:8000/_next/static/chunks/framework-19f3649580393c10.js)
Unexpected value 1.125rem parsing width attribute. [framework-19f3649580393c10.js:9:3251](http://localhost:8000/_next/static/chunks/framework-19f3649580393c10.js)
Unexpected value 1.125rem parsing height attribute. [framework-19f3649580393c10.js:9:3251](http://localhost:8000/_next/static/chunks/framework-19f3649580393c10.js)
Unexpected value 1.125rem parsing width attribute. [framework-19f3649580393c10.js:9:3251](http://localhost:8000/_next/static/chunks/framework-19f3649580393c10.js)
Unexpected value 1.125rem parsing height attribute. [framework-19f3649580393c10.js:9:3251](http://localhost:8000/_next/static/chunks/framework-19f3649580393c10.js)
TypeError: F is undefined
    NextJS 29
[framework-19f3649580393c10.js:9:69814](http://localhost:8000/_next/static/chunks/framework-19f3649580393c10.js)
TypeError: F is undefined
    NextJS 29
[main-54379c1fb512e6dc.js:1:10107](http://localhost:8000/_next/static/chunks/main-54379c1fb512e6dc.js)
A client-side exception has occurred, see here for more info: https://nextjs.org/docs/messages/client-side-exception-occurred [main-54379c1fb512e6dc.js:1:10124](http://localhost:8000/_next/static/chunks/main-54379c1fb512e6dc.js)
```

**Comment by langerdennis** [comment]
Same error here, Chrome 112 on ChromeOS, Android, iOS and also in Safari on iOS 16.4.1.

**Comment by afairgiant** [comment]
I'm having the same error on Windows 10 Chrome 113.0.5672.127 as well.
Hosted on Ubuntu 22.04.2 LTS

**Comment by IgnisDa** [comment]
Thank you for reporting this! Can you all try this on other browsers (like edge, safari etc) too? I want to collect a matrix of what all browsers are having this problem.

**Comment by afairgiant** [comment]
Using Windows 10:
I had same issue on Firefox 113.0.2  and Microsoft Edge Version 113.0.1774.50 (Official build) (64-bit).

**Comment by IgnisDa** [comment]
I released `v1.0.0-beta.9`. Can you please check with this version? (You will have to remove the old latest image using `docker rmi ghcr.io/ignisda/ryot:latest`)

**Comment by bonukai** [comment]
It works correctly in `v1.0.0-beta.9`

**Comment by Forceu** [comment]
Yes, it works for me as well now, thank you!

**Comment by afairgiant** [comment]
Works for me as well!
