### ISSUE TITLE
Reverse proxy error?

### ISSUE THREAD

**Issue by LnLcFlx** [IgnisDa/ryot#543]
After migrating successfully to `v4` (I can access ryot via the exposed port) I found that I can no longer access it via my reverse proxy (Traefik).
I always get Traefik's `404 page not found` although I haven't changed anything with the reverse proxy.

I'm running `v4.0.8-beta.1` because of #540. 
Logs are clean:
```
2024-01-01 14:08:12,532 INFO Set uid to user 1001 succeeded
2024-01-01 14:08:12,533 INFO supervisord started with pid 1
2024-01-01 14:08:13,535 INFO spawned: 'backend' with pid 8
2024-01-01 14:08:13,537 INFO spawned: 'frontend' with pid 9
2024-01-01 14:08:13,537 INFO spawned: 'reverse-proxy' with pid 10
2024-01-01 14:08:14,560 INFO success: backend entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2024-01-01 14:08:14,560 INFO success: frontend entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2024-01-01 14:08:14,560 INFO success: reverse-proxy entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
```

**Comment by LnLcFlx** [comment]
Ok I restarted my container multiple times (without recreating) and it always takes several minutes for it to be reachable though Traefik while `curl -L localhost:8000` in the Ryot container yields a response immediately. This is super weird...

**Comment by IgnisDa** [comment]
`docker exec -it ryot bash` and then show me the output of `/tmp/reverse-proxy-*` file.

**Comment by LnLcFlx** [comment]
`cat /tmp/reverse-proxy-*` gives
```
{"level":"info","ts":1704115558.894778,"msg":"using provided configuration","config_file":"/etc/caddy/Caddyfile","config_adapter":""}
{"level":"info","ts":1704115558.8955889,"logger":"admin","msg":"admin endpoint started","address":"localhost:2019","enforce_origin":false,"origins":["//[::1]:2019","//127.0.0.1:2019","//localhost:2019"]}
{"level":"warn","ts":1704115558.8956494,"logger":"http.auto_https","msg":"automatic HTTPS is completely disabled for server","server_name":"srv0"}
{"level":"info","ts":1704115558.8957298,"logger":"tls.cache.maintenance","msg":"started background certificate maintenance","cache":"0xc00068ca80"}
{"level":"info","ts":1704115558.8957877,"logger":"http.log","msg":"server running","name":"srv0","protocols":["h1","h2","h3"]}
{"level":"info","ts":1704115558.8957891,"logger":"tls","msg":"cleaning storage unit","description":"FileStorage:/home/ryot/.local/share/caddy"}
{"level":"info","ts":1704115558.8958228,"logger":"tls","msg":"finished cleaning storage units"}
{"level":"info","ts":1704115558.8958697,"msg":"autosaved config (load with --resume flag)","file":"/home/ryot/.config/caddy/autosave.json"}
{"level":"info","ts":1704115558.8958733,"msg":"serving initial configuration"}
{"level":"error","ts":1704115893.8762019,"logger":"http.handlers.reverse_proxy","msg":"aborting with incomplete response","upstream":"localhost:3000","duration":0.008613021,"request":{"remote_ip":"172.23.0.34","remote_port":"33104","client_ip":"172.23.0.34","proto":"HTTP/1.1","method":"GET","host":"CENSORED","uri":"/build/assets/components-MMZfPZkb.js","headers":{"Sec-Fetch-Mode":["cors"],"Sec-Fetch-Site":["same-origin"],"X-Forwarded-For":["172.23.0.34"],"Accept-Language":["de-DE,en-US;q=0.7,en;q=0.3"],"X-Real-Ip":["CENSORED"],"Accept":["*/*"],"X-Forwarded-Host":["CENSORED"],"X-Forwarded-Server":["8bdf44519115"],"User-Agent":["Mozilla/5.0 (X11; Linux x86_64; rv:122.0) Gecko/20100101 Firefox/122.0"],"Te":["trailers"],"Accept-Encoding":["gzip, deflate, br"],"Sec-Fetch-Dest":["empty"],"X-Forwarded-Port":["443"],"Dnt":["1"],"Referer":["https://CENSORED/"],"X-Forwarded-Proto":["http"],"Cookie":[]}},"error":"writing: write tcp 172.23.0.29:8000->172.23.0.34:33104: write: broken pipe"}
{"level":"error","ts":1704117299.346794,"logger":"http.handlers.reverse_proxy","msg":"aborting with incomplete response","upstream":"localhost:3000","duration":0.003927014,"request":{"remote_ip":"172.23.0.34","remote_port":"39426","client_ip":"172.23.0.34","proto":"HTTP/1.1","method":"GET","host":"CENSORED","uri":"/build/assets/components-MMZfPZkb.js","headers":{"Sec-Fetch-Site":["same-origin"],"Referer":["https://CENSORED/media/list/movie?sortBy=RELEASE_DATE&generalFilter=COMPLETED"],"Sec-Fetch-Dest":["empty"],"Accept-Language":["de-DE,en-US;q=0.7,en;q=0.3"],"Sec-Fetch-Mode":["cors"],"User-Agent":["Mozilla/5.0 (X11; Linux x86_64; rv:122.0) Gecko/20100101 Firefox/122.0"],"Accept-Encoding":["gzip, deflate, br"],"X-Real-Ip":["CENSORED"],"Dnt":["1"],"X-Forwarded-For":["172.23.0.34"],"X-Forwarded-Host":["CENSORED"],"Accept":["*/*"],"X-Forwarded-Server":["8bdf44519115"],"X-Forwarded-Port":["443"],"Te":["trailers"],"Cookie":[],"X-Forwarded-Proto":["http"]}},"error":"reading: context canceled"}
{"level":"error","ts":1704117299.3487856,"logger":"http.handlers.reverse_proxy","msg":"aborting with incomplete response","upstream":"localhost:3000","duration":0.005885031,"request":{"remote_ip":"172.23.0.34","remote_port":"36346","client_ip":"172.23.0.34","proto":"HTTP/1.1","method":"GET","host":"CENSORED","uri":"/build/assets/Group-4ecGglMs.js","headers":{"Accept-Encoding":["gzip, deflate, br"],"Accept-Language":["de-DE,en-US;q=0.7,en;q=0.3"],"User-Agent":["Mozilla/5.0 (X11; Linux x86_64; rv:122.0) Gecko/20100101 Firefox/122.0"],"Accept":["*/*"],"X-Forwarded-For":["172.23.0.34"],"X-Forwarded-Host":["CENSORED"],"X-Real-Ip":["CENSORED"],"X-Forwarded-Server":["8bdf44519115"],"Dnt":["1"],"Sec-Fetch-Site":["same-origin"],"Sec-Fetch-Dest":["empty"],"Cookie":[],"Sec-Fetch-Mode":["cors"],"Te":["trailers"],"X-Forwarded-Port":["443"],"Referer":["https://CENSORED/media/list/movie?sortBy=RELEASE_DATE&generalFilter=COMPLETED"],"X-Forwarded-Proto":["http"]}},"error":"reading: context canceled"}
{"level":"error","ts":1704117299.3615222,"logger":"http.handlers.reverse_proxy","msg":"aborting with incomplete response","upstream":"localhost:3000","duration":0.005007087,"request":{"remote_ip":"172.23.0.34","remote_port":"36638","client_ip":"172.23.0.34","proto":"HTTP/1.1","method":"GET","host":"CENSORED","uri":"/build/assets/InputBase-FfbUTlHH.js","headers":{"Te":["trailers"],"Sec-Fetch-Mode":["cors"],"Sec-Fetch-Dest":["empty"],"X-Forwarded-Server":["8bdf44519115"],"User-Agent":["Mozilla/5.0 (X11; Linux x86_64; rv:122.0) Gecko/20100101 Firefox/122.0"],"X-Forwarded-Port":["443"],"X-Forwarded-Proto":["http"],"Accept":["*/*"],"Referer":["https://CENSORED/media/list/movie?sortBy=RELEASE_DATE&generalFilter=COMPLETED"],"Cookie":[],"Dnt":["1"],"X-Forwarded-Host":["CENSORED"],"Accept-Encoding":["gzip, deflate, br"],"Accept-Language":["de-DE,en-US;q=0.7,en;q=0.3"],"Sec-Fetch-Site":["same-origin"],"X-Real-Ip":["CENSORED"],"X-Forwarded-For":["172.23.0.34"]}},"error":"reading: context canceled"}
```

**Comment by IgnisDa** [comment]
Can you do the same for frontend?

**Comment by LnLcFlx** [comment]
```
Error: No route matches URL "/sw.js"
    at getInternalRouterError (/home/ryot/node_modules/@remix-run/router/router.ts:4377:5)
    at Object.query (/home/ryot/node_modules/@remix-run/router/router.ts:2856:19)
    at handleDocumentRequestRR (/home/ryot/node_modules/@remix-run/server-runtime/dist/server.js:168:35)
    at requestHandler (/home/ryot/node_modules/@remix-run/server-runtime/dist/server.js:93:24)
    at /home/ryot/node_modules/@remix-run/express/dist/server.js:42:28
Error: No route matches URL "/workbox-1051b61c.js"
    at getInternalRouterError (/home/ryot/node_modules/@remix-run/router/router.ts:4377:5)
    at Object.query (/home/ryot/node_modules/@remix-run/router/router.ts:2856:19)
    at handleDocumentRequestRR (/home/ryot/node_modules/@remix-run/server-runtime/dist/server.js:168:35)
    at requestHandler (/home/ryot/node_modules/@remix-run/server-runtime/dist/server.js:93:24)
    at /home/ryot/node_modules/@remix-run/express/dist/server.js:42:28
ErrorResponseImpl {
  status: 404,
  statusText: 'Not Found',
  internal: true,
  data: 'Error: No route matches URL "/sw.js"',
  error: Error: No route matches URL "/sw.js"
      at getInternalRouterError (/home/ryot/node_modules/@remix-run/router/router.ts:4377:5)
      at Object.query (/home/ryot/node_modules/@remix-run/router/router.ts:2856:19)
      at handleDocumentRequestRR (/home/ryot/node_modules/@remix-run/server-runtime/dist/server.js:168:35)
      at requestHandler (/home/ryot/node_modules/@remix-run/server-runtime/dist/server.js:93:24)
      at /home/ryot/node_modules/@remix-run/express/dist/server.js:42:28
}
ErrorResponseImpl {
  status: 404,
  statusText: 'Not Found',
  internal: true,
  data: 'Error: No route matches URL "/workbox-1051b61c.js"',
  error: Error: No route matches URL "/workbox-1051b61c.js"
      at getInternalRouterError (/home/ryot/node_modules/@remix-run/router/router.ts:4377:5)
      at Object.query (/home/ryot/node_modules/@remix-run/router/router.ts:2856:19)
      at handleDocumentRequestRR (/home/ryot/node_modules/@remix-run/server-runtime/dist/server.js:168:35)
      at requestHandler (/home/ryot/node_modules/@remix-run/server-runtime/dist/server.js:93:24)
      at /home/ryot/node_modules/@remix-run/express/dist/server.js:42:28
}
Error: No route matches URL "/workbox-1051b61c.js"
    at getInternalRouterError (/home/ryot/node_modules/@remix-run/router/router.ts:4377:5)
    at Object.query (/home/ryot/node_modules/@remix-run/router/router.ts:2856:19)
    at handleDocumentRequestRR (/home/ryot/node_modules/@remix-run/server-runtime/dist/server.js:168:35)
    at requestHandler (/home/ryot/node_modules/@remix-run/server-runtime/dist/server.js:93:24)
    at /home/ryot/node_modules/@remix-run/express/dist/server.js:42:28
Error: No route matches URL "/sw.js"
    at getInternalRouterError (/home/ryot/node_modules/@remix-run/router/router.ts:4377:5)
    at Object.query (/home/ryot/node_modules/@remix-run/router/router.ts:2856:19)
    at handleDocumentRequestRR (/home/ryot/node_modules/@remix-run/server-runtime/dist/server.js:168:35)
    at requestHandler (/home/ryot/node_modules/@remix-run/server-runtime/dist/server.js:93:24)
    at /home/ryot/node_modules/@remix-run/express/dist/server.js:42:28
ErrorResponseImpl {
  status: 404,
  statusText: 'Not Found',
  internal: true,
  data: 'Error: No route matches URL "/workbox-1051b61c.js"',
  error: Error: No route matches URL "/workbox-1051b61c.js"
      at getInternalRouterError (/home/ryot/node_modules/@remix-run/router/router.ts:4377:5)
      at Object.query (/home/ryot/node_modules/@remix-run/router/router.ts:2856:19)
      at handleDocumentRequestRR (/home/ryot/node_modules/@remix-run/server-runtime/dist/server.js:168:35)
      at requestHandler (/home/ryot/node_modules/@remix-run/server-runtime/dist/server.js:93:24)
      at /home/ryot/node_modules/@remix-run/express/dist/server.js:42:28
}
ErrorResponseImpl {
  status: 404,
  statusText: 'Not Found',
  internal: true,
  data: 'Error: No route matches URL "/sw.js"',
  error: Error: No route matches URL "/sw.js"
      at getInternalRouterError (/home/ryot/node_modules/@remix-run/router/router.ts:4377:5)
      at Object.query (/home/ryot/node_modules/@remix-run/router/router.ts:2856:19)
      at handleDocumentRequestRR (/home/ryot/node_modules/@remix-run/server-runtime/dist/server.js:168:35)
      at requestHandler (/home/ryot/node_modules/@remix-run/server-runtime/dist/server.js:93:24)
      at /home/ryot/node_modules/@remix-run/express/dist/server.js:42:28
}
Error: No route matches URL "/sw.js"
    at getInternalRouterError (/home/ryot/node_modules/@remix-run/router/router.ts:4377:5)
    at Object.query (/home/ryot/node_modules/@remix-run/router/router.ts:2856:19)
    at handleDocumentRequestRR (/home/ryot/node_modules/@remix-run/server-runtime/dist/server.js:168:35)
    at requestHandler (/home/ryot/node_modules/@remix-run/server-runtime/dist/server.js:93:24)
    at /home/ryot/node_modules/@remix-run/express/dist/server.js:42:28
Error: No route matches URL "/workbox-1051b61c.js"
    at getInternalRouterError (/home/ryot/node_modules/@remix-run/router/router.ts:4377:5)
    at Object.query (/home/ryot/node_modules/@remix-run/router/router.ts:2856:19)
    at handleDocumentRequestRR (/home/ryot/node_modules/@remix-run/server-runtime/dist/server.js:168:35)
    at requestHandler (/home/ryot/node_modules/@remix-run/server-runtime/dist/server.js:93:24)
    at /home/ryot/node_modules/@remix-run/express/dist/server.js:42:28
ErrorResponseImpl {
  status: 404,
  statusText: 'Not Found',
  internal: true,
  data: 'Error: No route matches URL "/sw.js"',
  error: Error: No route matches URL "/sw.js"
      at getInternalRouterError (/home/ryot/node_modules/@remix-run/router/router.ts:4377:5)
      at Object.query (/home/ryot/node_modules/@remix-run/router/router.ts:2856:19)
      at handleDocumentRequestRR (/home/ryot/node_modules/@remix-run/server-runtime/dist/server.js:168:35)
      at requestHandler (/home/ryot/node_modules/@remix-run/server-runtime/dist/server.js:93:24)
      at /home/ryot/node_modules/@remix-run/express/dist/server.js:42:28
}
ErrorResponseImpl {
  status: 404,
  statusText: 'Not Found',
  internal: true,
  data: 'Error: No route matches URL "/workbox-1051b61c.js"',
  error: Error: No route matches URL "/workbox-1051b61c.js"
      at getInternalRouterError (/home/ryot/node_modules/@remix-run/router/router.ts:4377:5)
      at Object.query (/home/ryot/node_modules/@remix-run/router/router.ts:2856:19)
      at handleDocumentRequestRR (/home/ryot/node_modules/@remix-run/server-runtime/dist/server.js:168:35)
      at requestHandler (/home/ryot/node_modules/@remix-run/server-runtime/dist/server.js:93:24)
      at /home/ryot/node_modules/@remix-run/express/dist/server.js:42:28
}
Error: No route matches URL "/sw.js"
    at getInternalRouterError (/home/ryot/node_modules/@remix-run/router/router.ts:4377:5)
    at Object.query (/home/ryot/node_modules/@remix-run/router/router.ts:2856:19)
    at handleDocumentRequestRR (/home/ryot/node_modules/@remix-run/server-runtime/dist/server.js:168:35)
    at requestHandler (/home/ryot/node_modules/@remix-run/server-runtime/dist/server.js:93:24)
    at /home/ryot/node_modules/@remix-run/express/dist/server.js:42:28
Error: No route matches URL "/workbox-1051b61c.js"
    at getInternalRouterError (/home/ryot/node_modules/@remix-run/router/router.ts:4377:5)
    at Object.query (/home/ryot/node_modules/@remix-run/router/router.ts:2856:19)
    at handleDocumentRequestRR (/home/ryot/node_modules/@remix-run/server-runtime/dist/server.js:168:35)
    at requestHandler (/home/ryot/node_modules/@remix-run/server-runtime/dist/server.js:93:24)
    at /home/ryot/node_modules/@remix-run/express/dist/server.js:42:28
ErrorResponseImpl {
  status: 404,
  statusText: 'Not Found',
  internal: true,
  data: 'Error: No route matches URL "/sw.js"',
  error: Error: No route matches URL "/sw.js"
      at getInternalRouterError (/home/ryot/node_modules/@remix-run/router/router.ts:4377:5)
      at Object.query (/home/ryot/node_modules/@remix-run/router/router.ts:2856:19)
      at handleDocumentRequestRR (/home/ryot/node_modules/@remix-run/server-runtime/dist/server.js:168:35)
      at requestHandler (/home/ryot/node_modules/@remix-run/server-runtime/dist/server.js:93:24)
      at /home/ryot/node_modules/@remix-run/express/dist/server.js:42:28
}
ErrorResponseImpl {
  status: 404,
  statusText: 'Not Found',
  internal: true,
  data: 'Error: No route matches URL "/workbox-1051b61c.js"',
  error: Error: No route matches URL "/workbox-1051b61c.js"
      at getInternalRouterError (/home/ryot/node_modules/@remix-run/router/router.ts:4377:5)
      at Object.query (/home/ryot/node_modules/@remix-run/router/router.ts:2856:19)
      at handleDocumentRequestRR (/home/ryot/node_modules/@remix-run/server-runtime/dist/server.js:168:35)
      at requestHandler (/home/ryot/node_modules/@remix-run/server-runtime/dist/server.js:93:24)
      at /home/ryot/node_modules/@remix-run/express/dist/server.js:42:28
}
[remix-serve] http://localhost:3000 (http://192.168.128.3:3000)
GET / 302 - - 16.345 ms
GET /auth/login?redirectTo=/ 200 - - 24.486 ms
GET / 302 - - 3.845 ms
GET /auth/login?redirectTo=/ 200 - - 9.053 ms
GET /media/list/movie?sortBy=RELEASE_DATE&generalFilter=COMPLETED 200 - - 146.214 ms
GET /sw.js 404 - - 33.232 ms
GET /workbox-1051b61c.js 404 - - 7.099 ms
GET /media/list/movie?sortBy=RELEASE_DATE&generalFilter=COMPLETED&_data=root 200 - - 2.024 ms
GET /media/list/movie?sortBy=RELEASE_DATE&generalFilter=COMPLETED&_data=routes%2F_dashboard 200 - - 9.245 ms
GET /media/list/movie?sortBy=RELEASE_DATE&generalFilter=COMPLETED&_data=routes%2F_dashboard.media.%24action.%24lot 200 - - 87.824 ms
GET /workbox-1051b61c.js 404 - - 3.263 ms
GET /sw.js 404 - - 2.998 ms
GET /?_data=root 200 - - 1.210 ms
GET /?_data=routes%2F_dashboard 200 - - 8.181 ms
GET /?_data=routes%2F_dashboard._index 200 - - 23.917 ms
GET /sw.js 404 - - 2.710 ms
GET /workbox-1051b61c.js 404 - - 2.564 ms
GET /sw.js 404 - - 3.083 ms
GET /workbox-1051b61c.js 404 - - 2.800 ms
```
where
```
GET / 302 - - 16.345 ms
GET /auth/login?redirectTo=/ 200 - - 24.486 ms
GET / 302 - - 3.845 ms
GET /auth/login?redirectTo=/ 200 - - 9.053 ms
```
was issued in the container `curl -L localhost:8000` upon start and the rest after it was accessible via Traefik.

**Comment by IgnisDa** [comment]
`curl -L localhost:8000` was the out an HTML response?

**Comment by LnLcFlx** [comment]
Yes
```html
<!DOCTYPE html><html lang="en"><head><meta charSet="utf-8"/><meta name="viewport" content="minimum-scale=1, initial-scale=1, width=device-width, shrink-to-fit=no, user-scalable=no, viewport-fit=cover"/><link rel="manifest" href="/manifest.json"/><title>Login | Ryot</title><link rel="stylesheet" href="/build/assets/root-q46RlPPt.css"/><link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png"/><link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png"/><link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;600;700;800;900&amp;display=swap"/><link rel="stylesheet" href="/build/assets/auth-Y3BVYz_p.css"/><script data-mantine-script="true">document.documentElement.setAttribute("data-mantine-color-scheme", 'light');</script></head><body><style data-mantine-styles="true">:root{--mantine-font-family: Poppins;--mantine-font-family-headings: Poppins;}</style><style data-mantine-styles="classes">@media (max-width: 35.99375em) {.mantine-visible-from-xs {display: none !important;}}@media (min-width: 36em) {.mantine-hidden-from-xs {display: none !important;}}@media (max-width: 47.99375em) {.mantine-visible-from-sm {display: none !important;}}@media (min-width: 48em) {.mantine-hidden-from-sm {display: none !important;}}@media (max-width: 61.99375em) {.mantine-visible-from-md {display: none !important;}}@media (min-width: 62em) {.mantine-hidden-from-md {display: none !important;}}@media (max-width: 74.99375em) {.mantine-visible-from-lg {display: none !important;}}@media (min-width: 75em) {.mantine-hidden-from-lg {display: none !important;}}@media (max-width: 87.99375em) {.mantine-visible-from-xl {display: none !important;}}@media (min-width: 88em) {.mantine-hidden-from-xl {display: none !important;}}</style><div style="flex-grow:1;min-height:100vh" class="m-8bffd616 mnt-Flex-root __m__-R9p"><form method="post" action="/auth/login?redirectTo=/" style="margin:auto" class="_form_1acch_1" novalidate=""><div class="m-46b77525 mnt-InputWrapper-root mnt-TextInput-root"><label class="m-8fdc1311 mnt-InputWrapper-label mnt-TextInput-label" data-required="true" for="username-input" id="username-input-label">Username<span class="m-78a94662 mnt-InputWrapper-required mnt-TextInput-required" aria-hidden="true"> *</span></label><div class="m-6c018570 mnt-Input-wrapper mnt-TextInput-wrapper" data-variant="default"><input class="m-8fb7ebe7 mnt-Input-input mnt-TextInput-input" data-variant="default" name="username" autofocus="" required="" aria-invalid="false" id="username-input"/></div></div><div style="margin-top:var(--mantine-spacing-md)" class="m-f61ca620 mnt-PasswordInput-root m-46b77525 mnt-InputWrapper-root mnt-PasswordInput-root"><label class="m-8fdc1311 mnt-InputWrapper-label mnt-PasswordInput-label" data-required="true" for="password-input" id="password-input-label">Password<span class="m-78a94662 mnt-InputWrapper-required mnt-PasswordInput-required" aria-hidden="true"> *</span></label><div style="--input-left-section-pointer-events:none;--input-right-section-pointer-events:all" class="m-6c018570 mnt-Input-wrapper mnt-PasswordInput-wrapper" data-variant="default" data-with-right-section="true"><div class="m-ccf8da4c m-8fb7ebe7 mnt-Input-input mnt-PasswordInput-input" data-variant="default"><input required="" class="m-f2d85dd2 mnt-PasswordInput-innerInput" id="password-input" name="password" autoComplete="off" type="password"/></div><div data-position="right" class="m-82577fc2 mnt-Input-section mnt-PasswordInput-section"><button style="--ai-bg:transparent;--ai-hover:var(--mantine-color-gray-light-hover);--ai-color:var(--mantine-color-gray-light-color);--ai-bd:calc(0.0625rem * var(--mantine-scale)) solid transparent" class="mantine-focus-auto mantine-active m-b1072d44 mnt-PasswordInput-visibilityToggle m-8d3f4000 mnt-ActionIcon-root m-87cf2631 mnt-UnstyledButton-root" data-variant="subtle" type="button" aria-hidden="true" tabindex="-1"><svg viewBox="0 0 15 15" fill="none" xmlns="http://www.w3.org/2000/svg" style="width:var(--psi-icon-size);height:var(--psi-icon-size)"><path d="M7.5 11C4.80285 11 2.52952 9.62184 1.09622 7.50001C2.52952 5.37816 4.80285 4 7.5 4C10.1971 4 12.4705 5.37816 13.9038 7.50001C12.4705 9.62183 10.1971 11 7.5 11ZM7.5 3C4.30786 3 1.65639 4.70638 0.0760002 7.23501C-0.0253338 7.39715 -0.0253334 7.60288 0.0760014 7.76501C1.65639 10.2936 4.30786 12 7.5 12C10.6921 12 13.3436 10.2936 14.924 7.76501C15.0253 7.60288 15.0253 7.39715 14.924 7.23501C13.3436 4.70638 10.6921 3 7.5 3ZM7.5 9.5C8.60457 9.5 9.5 8.60457 9.5 7.5C9.5 6.39543 8.60457 5.5 7.5 5.5C6.39543 5.5 5.5 6.39543 5.5 7.5C5.5 8.60457 6.39543 9.5 7.5 9.5Z" fill="currentColor" fill-rule="evenodd" clip-rule="evenodd"></path></svg></button></div></div></div><input name="redirectTo" type="hidden" value="/"/><button style="margin-top:var(--mantine-spacing-md);width:100%" class="mantine-focus-auto mantine-active m-77c9d27d mnt-Button-root m-87cf2631 mnt-UnstyledButton-root" type="submit" id="submit-button"><span class="m-a25b86ee mnt-Button-loader" aria-hidden="true"><span style="--loader-size:calc(var(--button-height) / 1.8);--loader-color:var(--button-color)" class="m-b34414df m-5ae2e3c mnt-Loader-root"></span></span><span class="m-80f1301b mnt-Button-inner"><span class="m-811560b9 mnt-Button-label">Login</span></span></button><div style="text-align:right;margin-top:var(--mantine-spacing-lg)" class="">Need an account? Register<!-- --> <a class="mantine-focus-auto m-849cf0da m-b6d8b162 mnt-Text-root mnt-Anchor-root" data-underline="hover" href="/auth/register">here</a>.</div></form></div><script>((STORAGE_KEY, restoreKey) => {
    if (!window.history.state || !window.history.state.key) {
      let key = Math.random().toString(32).slice(2);
      window.history.replaceState({
        key
      }, "");
    }
    try {
      let positions = JSON.parse(sessionStorage.getItem(STORAGE_KEY) || "{}");
      let storedY = positions[restoreKey || window.history.state.key];
      if (typeof storedY === "number") {
        window.scrollTo(0, storedY);
      }
    } catch (error) {
      console.error(error);
      sessionStorage.removeItem(STORAGE_KEY);
    }
  })("positions", null)</script><link rel="modulepreload" href="/build/manifest-24c94f78.js"/><link rel="modulepreload" href="/build/assets/entry.client-9Zz0LWJv.js"/><link rel="modulepreload" href="/build/assets/components-MMZfPZkb.js"/><link rel="modulepreload" href="/build/assets/client-W5jsqtgi.js"/><link rel="modulepreload" href="/build/assets/use-media-query-YdDJUUqU.js"/><link rel="modulepreload" href="/build/assets/UnstyledButton-eRaApKmY.js"/><link rel="modulepreload" href="/build/assets/use-isomorphic-effect-xGDqcmIg.js"/><link rel="modulepreload" href="/build/assets/use-reduced-motion-f4z6hyvv.js"/><link rel="modulepreload" href="/build/assets/Transition-bdiiALsl.js"/><link rel="modulepreload" href="/build/assets/use-id-1NJmDrrU.js"/><link rel="modulepreload" href="/build/assets/get-default-z-index-XPbdk4nn.js"/><link rel="modulepreload" href="/build/assets/Group-4ecGglMs.js"/><link rel="modulepreload" href="/build/assets/CloseButton-SbnPjG0e.js"/><link rel="modulepreload" href="/build/assets/Paper-rfJvYC7F.js"/><link rel="modulepreload" href="/build/assets/use-window-event-WIUHOaUT.js"/><link rel="modulepreload" href="/build/assets/Loader-GOHKIdc_.js"/><link rel="modulepreload" href="/build/assets/Modal-thyTw7O-.js"/><link rel="modulepreload" href="/build/assets/Stack-ckQ02OUp.js"/><link rel="modulepreload" href="/build/assets/Text-E4c_dXB7.js"/><link rel="modulepreload" href="/build/assets/Button-1t1Zwk-e.js"/><link rel="modulepreload" href="/build/assets/QueryClientProvider-XVCQvwDs.js"/><link rel="modulepreload" href="/build/assets/index-L9jAfYBe.js"/><link rel="modulepreload" href="/build/assets/notifications.store-mnGfAv7Z.js"/><link rel="modulepreload" href="/build/assets/confirmation-lV0KHj3b.js"/><link rel="modulepreload" href="/build/assets/ActionIcon-MCVTNPaS.js"/><link rel="modulepreload" href="/build/assets/Alert--tz7EZmz.js"/><link rel="modulepreload" href="/build/assets/px-Krd3uLkV.js"/><link rel="modulepreload" href="/build/assets/Flex-TbNNCVBA.js"/><link rel="modulepreload" href="/build/assets/root-auOUEbas.js"/><link rel="modulepreload" href="/build/assets/graphql-ilrmc3Xn.js"/><link rel="modulepreload" href="/build/assets/createReactComponent-hkHkKZPF.js"/><link rel="modulepreload" href="/build/assets/InputBase-FfbUTlHH.js"/><link rel="modulepreload" href="/build/assets/use-resolved-styles-api-NY0vTEdH.js"/><link rel="modulepreload" href="/build/assets/use-uncontrolled-homVU-RM.js"/><link rel="modulepreload" href="/build/assets/index-PuvrNLA3.js"/><link rel="modulepreload" href="/build/assets/generals-EyvDIcXY.js"/><link rel="modulepreload" href="/build/assets/auth.module-kUm2z_oR.js"/><link rel="modulepreload" href="/build/assets/TextInput--2d9KcCh.js"/><link rel="modulepreload" href="/build/assets/PasswordInput-8R3IQc0_.js"/><link rel="modulepreload" href="/build/assets/Anchor-yppJRoDl.js"/><link rel="modulepreload" href="/build/assets/auth.login-fOio5C0k.js"/><script>window.__remixContext = {"url":"/auth/login","state":{"loaderData":{"root":{"envData":{},"toast":null,"defaultColorScheme":"light"},"routes/auth.login":{"enabledFeatures":{"signupAllowed":true},"coreDetails":{"defaultCredentials":false}}},"actionData":null,"errors":null},"future":{"v3_fetcherPersist":false}};</script><script type="module" async="">import "/build/manifest-24c94f78.js";
import * as route0 from "/build/assets/root-auOUEbas.js";
import * as route1 from "/build/assets/auth.login-fOio5C0k.js";
window.__remixRouteModules = {"root":route0,"routes/auth.login":route1};
  statusText: 'Not Found',
import("/build/assets/entry.client-9Zz0LWJv.js");</script></body></html>
```

**Comment by IgnisDa** [comment]
Can you show your docker compose?

**Comment by LnLcFlx** [comment]
```yml
version: "3.9"
services:
...
  ryot:
    image: ghcr.io/ignisda/ryot:unstable
    container_name: ryot
    depends_on:
      - ryot-db
    environment:
      - TZ=${TZ}
      - DATABASE_URL=postgres://ryot:${RYOT_PASSWORD}@ryot-db:5432/ryot
    networks:
      - ryot
      - traefik
    labels:
      - traefik.enable=true
      - traefik.http.routers.ryot.entrypoints=websecure
      - traefik.http.routers.ryot.rule=Host(`ryot.${DOMAIN}`)
      - traefik.http.services.ryot.loadbalancer.server.port=8000
  ryot-db:
    image: postgres:16-alpine
    container_name: ryot-db
    restart: unless-stopped
    environment:
      - POSTGRES_DB=ryot
      - POSTGRES_USER=ryot
      - POSTGRES_PASSWORD=${RYOT_PASSWORD}
    volumes:
      - ${VOL}/ryot/db:/var/lib/postgresql/data
    networks:
      - ryot
...
networks:
  - traefik
  - ryot
```

**Comment by IgnisDa** [comment]
I am not sure how to debug this since the Ryot side looks fine. Is there anything in Traefik logs that might point to a solution?

**Comment by LnLcFlx** [comment]
No. I don't think it's any use to you but if you need it I can send it. I might need a minute to censor it.

**Comment by IgnisDa** [comment]
No need then. I think you should ask this question on traefik forums - the problem here essentially seems to be that traefik is not able to work in front of another reverse proxy.

**Comment by LnLcFlx** [comment]
https://community.traefik.io/t/traefik-in-front-of-other-reverse-proxy-takes-several-minutes-to-work-otherwise-404/20941

**Comment by IgnisDa** [comment]
Great please update here when you find the solution.

**Comment by IgnisDa** [comment]
Closing due to inactivity.

**Comment by LnLcFlx** [comment]
Still not resolved

**Comment by Kwbmm** [comment]
I'm experiencing the same problem :(

**Comment by Millio345** [comment]
I've figured out the reason for this issue: 
Apparently Traefik only adds the container when it reports as being healthy, and the health check only runs 5 minutes after starting the container, so until that time the container's health is stuck at 'starting'.

I believe using the start-period and start-interval health check options to run it every few seconds during startup will fix this issue.

**Comment by LnLcFlx** [comment]
Yes that's it! After adding
```yaml
healthcheck:
  interval: 30s
```
to the ryot container, it is accessible after 30s.
The issue is the unusually high value of 5min in the [Dockerfile](https://github.com/IgnisDa/ryot/blob/8713dc58c9b37397cfbc0cc3dbe239dfed6d6e60/Dockerfile#L59C1-L59C12).

**Comment by IgnisDa** [comment]
@LnLcFlx I will remove the healthcheck command completely from the dockerfile.

**Comment by IgnisDa** [comment]
Thanks for the help @Millio345 and @LnLcFlx.
