### ISSUE TITLE
Clean docker deployment doesn't work

### ISSUE THREAD

**Issue by naxhh** [IgnisDa/ryot#572]
A new clean installment:

```
version: "3.9"

services:
  ryot-db:
    image: postgres:16-alpine
    restart: unless-stopped
    volumes:
      - postgres_storage:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - TZ=Europe/Madrid
    container_name: ryot-db

  ryot:
    image: "ghcr.io/ignisda/ryot:latest"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@ryot-db:5432/postgres
      - TZ=Europe/Madrid
    ports:
      - "7000:8000"
    pull_policy: always
    container_name: ryot

volumes:
  postgres_storage:
```

After startup I visit http://192.168.1.248:7000/

```
[frontend] GET /favicon.ico 404 - - 21.782 ms
[frontend] ClientError: missing field `tag_name` at line 1 column 278: {"response":{"data":null,"errors":[{"message":"missing field `tag_name` at line 1 column 278","locations":[{"line":2,"column":3}],"path":["coreDetails"]}],"status":200,"headers":{}},"request":{"query":"query CoreDetails {\n  coreDetails {\n    version\n    timezone\n    authorName\n    repositoryLink\n    docsLink\n    defaultCredentials\n    credentialsChangeAllowed\n    preferencesChangeAllowed\n    itemDetailsHeight\n    reviewsDisabled\n    videosDisabled\n    upgrade\n    pageLimit\n    deployAdminJobsAllowed\n  }\n}"}}
[frontend]     at makeRequest (file:///home/ryot/node_modules/graphql-request/src/index.ts:426:11)
[frontend]     at processTicksAndRejections (node:internal/process/task_queues:95:5)
[frontend]     at getCoreDetails (file:///home/ryot/build/server/index.js?t=1705151088000:963:27)
[frontend]     at loader$1 (file:///home/ryot/build/server/index.js?t=1705151088000:12235:23)
[frontend]     at Object.callRouteLoaderRR (/home/ryot/node_modules/@remix-run/server-runtime/dist/data.js:52:16)
[frontend]     at callLoaderOrAction (/home/ryot/node_modules/@remix-run/router/router.ts:4011:16)
[frontend]     at async Promise.all (index 1)
[frontend]     at loadRouteData (/home/ryot/node_modules/@remix-run/router/router.ts:3298:19)
[frontend]     at queryImpl (/home/ryot/node_modules/@remix-run/router/router.ts:3076:20)
[frontend]     at Object.query (/home/ryot/node_modules/@remix-run/router/router.ts:2952:18) {
[frontend]   response: {
[frontend]     data: null,
[frontend]     errors: [ [Object] ],
[frontend]     status: 200,
[frontend]     headers: Headers { [Symbol(map)]: [Object: null prototype] }
[frontend]   },
[frontend]   request: {
[frontend]     query: 'query CoreDetails {\n' +
[frontend]       '  coreDetails {\n' +
[frontend]       '    version\n' +
[frontend]       '    timezone\n' +
[frontend]       '    authorName\n' +
[frontend]       '    repositoryLink\n' +
[frontend]       '    docsLink\n' +
[frontend]       '    defaultCredentials\n' +
[frontend]       '    credentialsChangeAllowed\n' +
[frontend]       '    preferencesChangeAllowed\n' +
[frontend]       '    itemDetailsHeight\n' +
[frontend]       '    reviewsDisabled\n' +
[frontend]       '    videosDisabled\n' +
[frontend]       '    upgrade\n' +
[frontend]       '    pageLimit\n' +
[frontend]       '    deployAdminJobsAllowed\n' +
[frontend]       '  }\n' +
[frontend]       '}',
[frontend]     variables: undefined
[frontend]   }
      
[frontend] }
[frontend] [Error: Unexpected Server Error]
[frontend] GET /auth/login?redirectTo=/ 500 - - 355.975 ms
[frontend] ClientError: missing field `tag_name` at line 1 column 278: {"response":{"data":null,"errors":[{"message":"missing field `tag_name` at line 1 column 278","locations":[{"line":2,"column":3}],"path":["coreDetails"]}],"status":200,"headers":{}},"request":{"query":"query CoreDetails {\n  coreDetails {\n    version\n    timezone\n    authorName\n    repositoryLink\n    docsLink\n    defaultCredentials\n    credentialsChangeAllowed\n    preferencesChangeAllowed\n    itemDetailsHeight\n    reviewsDisabled\n    videosDisabled\n    upgrade\n    pageLimit\n    deployAdminJobsAllowed\n  }\n}"}}
[frontend]     at makeRequest (file:///home/ryot/node_modules/graphql-request/src/index.ts:426:11)
[frontend]     at processTicksAndRejections (node:internal/process/task_queues:95:5)
[frontend]     at getCoreDetails (file:///home/ryot/build/server/index.js?t=1705151088000:963:27)
[frontend]     at loader$1 (file:///home/ryot/build/server/index.js?t=1705151088000:12235:23)
[frontend]     at Object.callRouteLoaderRR (/home/ryot/node_modules/@remix-run/server-runtime/dist/data.js:52:16)
[frontend]     at callLoaderOrAction (/home/ryot/node_modules/@remix-run/router/router.ts:4011:16)
[frontend]     at async Promise.all (index 1)
[frontend]     at loadRouteData (/home/ryot/node_modules/@remix-run/router/router.ts:3298:19)
[frontend]     at queryImpl (/home/ryot/node_modules/@remix-run/router/router.ts:3076:20)
[frontend]     at Object.query (/home/ryot/node_modules/@remix-run/router/router.ts:2952:18) {
[frontend]   response: {
[frontend]     data: null,
[frontend]     errors: [ [Object] ],
[frontend]     status: 200,
[frontend]     headers: Headers { [Symbol(map)]: [Object: null prototype] }
[frontend]   },
[frontend]   request: {
[frontend]     query: 'query CoreDetails {\n' +
[frontend]       '  coreDetails {\n' +
[frontend]       '    version\n' +
[frontend]       '    timezone\n' +
[frontend]       '    authorName\n' +
[frontend]       '    repositoryLink\n' +
[frontend]       '    docsLink\n' +
[frontend]       '    defaultCredentials\n' +
[frontend]       '    credentialsChangeAllowed\n' +
[frontend]       '    preferencesChangeAllowed\n' +
[frontend]       '    itemDetailsHeight\n' +
[frontend]       '    reviewsDisabled\n' +
[frontend]       '    videosDisabled\n' +
[frontend]       '    upgrade\n' +
[frontend]       '    pageLimit\n' +
[frontend]       '    deployAdminJobsAllowed\n' +
[frontend]       '  }\n' +
[frontend]       '}',
[frontend]     variables: undefined
[frontend]   }
      
[frontend] }
[frontend] [Error: Unexpected Server Error]
[frontend] GET /auth/login?redirectTo=/ 500 - - 77.355 ms
```

Tested tags:
- latest
- 4.1.2
- 4.0.15

For testing sake 3.5.4 works

**Comment by IgnisDa** [comment]
This happens when GitHub rate limits your machine. There's probably another application on your machine that's making a lot of requests to GitHub api. 

I'll add some error handling and release it with #576.
