### ISSUE TITLE
'PORT' environment does not work in version above 3.4.5

### ISSUE THREAD

**Issue by equuskk** [IgnisDa/ryot#586]
I'm trying to install ryot (latest / 4.0+ version) in docker and I need to specify a custom port. When I try to do this via the 'PORT' environment variable, I get the following error:

```
[frontend] Error: listen EADDRINUSE: address already in use :::20391
[frontend]     at Server.setupListenHandle [as _listen2] (node:net:1872:16)
[frontend]     at listenInCluster (node:net:1920:12)
[frontend]     at Server.listen (node:net:2008:7)
[frontend]     at Function.listen (/home/ryot/node_modules/express/lib/application.js:635:24)
[frontend]     at run (/home/ryot/node_modules/@remix-run/serve/dist/cli.js:126:86)
[frontend] npx remix-serve ./build/index.js exited with code 1
--> Sending SIGTERM to other processes..
node:events:492
      throw er; // Unhandled 'error' event
      ^
Error: spawn ps ENOENT
    at ChildProcess._handle.onexit (node:internal/child_process:286:19)
    at onErrorNT (node:internal/child_process:484:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
Emitted 'error' event on ChildProcess instance at:
    at ChildProcess._handle.onexit (node:internal/child_process:292:12)
    at onErrorNT (node:internal/child_process:484:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
      
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn ps',
  path: 'ps',
  spawnargs: [ '-o', 'pid', '--no-headers', '--ppid', 19 ]
}
```

But if you specify version **3.4.5**, then the server starts up.

**Comment by IgnisDa** [comment]
Released with `v4.1.5`.
