### ISSUE TITLE
[BUG] Application error when deploying the stack the first time

### ISSUE THREAD

**Issue by WoBuGs** [IgnisDa/ryot#647]
The following error is displayed after spinning up the application for the first time:

![image](https://github.com/IgnisDa/ryot/assets/5580042/5c339788-428f-43ad-95c4-ee759eaeea1e)

And the logs from the container:

```
2024-02-18T16:39:44.502671442Z [frontend]     at queryImpl (/home/ryot/node_modules/@remix-run/router/router.ts:3076:20)
2024-02-18T16:39:44.502674069Z [frontend]     at Object.query (/home/ryot/node_modules/@remix-run/router/router.ts:2952:18) {
2024-02-18T16:39:44.502676562Z [frontend]   response: {
2024-02-18T16:39:44.502679013Z [frontend]     data: null,
2024-02-18T16:39:44.502681500Z [frontend]     errors: [ [Object] ],
2024-02-18T16:39:44.502683981Z [frontend]     status: 200,
2024-02-18T16:39:44.502686425Z [frontend]     headers: Headers { [Symbol(map)]: [Object: null prototype] }
2024-02-18T16:39:44.502688974Z [frontend]   },
2024-02-18T16:39:44.502691369Z [frontend]   request: {
2024-02-18T16:39:44.502693983Z [frontend]     query: 'query CoreDetails {\n' +
2024-02-18T16:39:44.502696555Z [frontend]       '  coreDetails {\n' +
2024-02-18T16:39:44.502698985Z [frontend]       '    version\n' +
2024-02-18T16:39:44.502701407Z [frontend]       '    timezone\n' +
2024-02-18T16:39:44.502703843Z [frontend]       '    authorName\n' +
2024-02-18T16:39:44.502706251Z [frontend]       '    repositoryLink\n' +
2024-02-18T16:39:44.502708702Z [frontend]       '    docsLink\n' +
2024-02-18T16:39:44.502711825Z [frontend]       '    defaultCredentials\n' +
2024-02-18T16:39:44.502714261Z [frontend]       '    credentialsChangeAllowed\n' +
2024-02-18T16:39:44.502716639Z [frontend]       '    preferencesChangeAllowed\n' +
2024-02-18T16:39:44.502719082Z [frontend]       '    itemDetailsHeight\n' +
2024-02-18T16:39:44.502721459Z [frontend]       '    reviewsDisabled\n' +
2024-02-18T16:39:44.502723946Z [frontend]       '    videosDisabled\n' +
2024-02-18T16:39:44.502726334Z [frontend]       '    upgrade\n' +
2024-02-18T16:39:44.502728817Z [frontend]       '    pageLimit\n' +
2024-02-18T16:39:44.502731122Z [frontend]       '    deployAdminJobsAllowed\n' +
2024-02-18T16:39:44.502733547Z [frontend]       '  }\n' +
2024-02-18T16:39:44.502738551Z [frontend]       '}',
2024-02-18T16:39:44.502741057Z [frontend]     variables: undefined
2024-02-18T16:39:44.502743603Z [frontend]   }
2024-02-18T16:39:44.502745959Z [frontend] }
2024-02-18T16:39:44.507350420Z [frontend] [Error: Unexpected Server Error]
2024-02-18T16:39:44.516819643Z [frontend] GET /auth/login?redirectTo=%2F 500 - - 177.297 ms
```

My set-up is quite straight forward, apart from small changes to the proposed `docker-compose.yml` file, but I do not think that is causing the issue.

Have you encountered something like this before?

Here is my `docker-compose.yml` file:

```
version: "3.9"

services:
  ryot-db:
    image: postgres:16-alpine
    container_name: ryot-db
    restart: unless-stopped
    volumes:
      - ryot_db:/var/lib/postgresql/data
    networks:
      - ryot
    environment:
      - POSTGRES_PASSWORD=***
      - POSTGRES_USER=***
      - POSTGRES_DB=***
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ***']
      interval: 5s
      timeout: 5s
      retries: 5

  ryot:
    image: "ghcr.io/ignisda/ryot:latest"
    container_name: ryot
    restart: unless-stopped
    depends_on:
      - ryot-db
    environment:
      - DATABASE_URL=postgres://***:***@ryot-db:5432/***
      - DISABLE_TELEMETRY=true
      - TZ=Europe/Paris
      - VIDEO_GAMES_TWITCH_CLIENT_ID=***
      - VIDEO_GAMES_TWITCH_CLIENT_SECRET=***
    healthcheck:
      test: ["CMD", "curl", "-fs", "-S", "--max-time", "2", "http://localhost:8000/backend/config"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - ryot
      - proxy_ryot
    expose:
      - 8000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ryot.entrypoints=https"
      - "traefik.http.routers.ryot.rule=Host(`ryot.***`)"
      - "traefik.http.routers.ryot.tls=true"

volumes:
  ryot_db:

networks:
  ryot:
  proxy_ryot:
    external: true
```

**Comment by IgnisDa** [comment]
Could it be related to #543?

**Comment by IgnisDa** [comment]
I think you haven't attached the complete logs since I can't see the backend ones.

**Comment by LnLcFlx** [comment]
I also saw this error a couple of times though I don't remember under what circumstsnces.

**Comment by IgnisDa** [comment]
I don't really understand what traefik is doing differently that makes Ryot stop working. @LnLcFlx the container runs a reverse proxy in frontend of the backend and frontend servers. Would that somehow affect traefik's functioning?

**Comment by WoBuGs** [comment]
Hi all,
After spinning the stack back up today, it worked just fine. Maybe this error was due to some provisionning during first launch or something?
I'm closing this issue now since it resolved itself :)

Thank you for the quick replies!
