### ISSUE TITLE
[Bug] Application error when trying to go to dashboard

### ISSUE THREAD

**Issue by RowanBee** [IgnisDa/ryot#662]
Fresh setup, just input my movies. I told it to synchronize, and then I clicked dashboard and now all I see is "Application error". This does not occur on any other page.

![image](https://github.com/IgnisDa/ryot/assets/47164828/485b098f-b142-46ce-87ed-31c80cd17951)

2024-02-28 21:47:36 ryot     | [frontend] TypeError: Cannot read properties of undefined (reading 'id')
2024-02-28 21:47:36 ryot     | [frontend]     at loader$4 (file:///home/ryot/build/server/index.js?t=1709032867000:11874:47)
2024-02-28 21:47:36 ryot     | [frontend]     at processTicksAndRejections (node:internal/process/task_queues:95:5)
2024-02-28 21:47:36 ryot     | [frontend]     at Object.callRouteLoaderRR (/home/ryot/node_modules/@remix-run/server-runtime/dist/data.js:52:16)
2024-02-28 21:47:36 ryot     | [frontend]     at callLoaderOrAction (/home/ryot/node_modules/@remix-run/router/router.ts:4020:16)
2024-02-28 21:47:36 ryot     | [frontend]     at async Promise.all (index 2)
2024-02-28 21:47:36 ryot     | [frontend]     at loadRouteData (/home/ryot/node_modules/@remix-run/router/router.ts:3297:19)
2024-02-28 21:47:36 ryot     | [frontend]     at queryImpl (/home/ryot/node_modules/@remix-run/router/router.ts:3078:20)
2024-02-28 21:47:36 ryot     | [frontend]     at Object.query (/home/ryot/node_modules/@remix-run/router/router.ts:2954:18)
2024-02-28 21:47:36 ryot     | [frontend]     at handleDocumentRequestRR (/home/ryot/node_modules/@remix-run/server-runtime/dist/server.js:182:15)
2024-02-28 21:47:36 ryot     | [frontend]     at requestHandler (/home/ryot/node_modules/@remix-run/server-runtime/dist/server.js:107:18)
2024-02-28 21:47:36 ryot     | [frontend] [Error: Unexpected Server Error]
2024-02-28 21:47:36 ryot     | [frontend] GET / 500 - - 19.717 ms

**Comment by IgnisDa** [comment]
Can you open the collections page? Please attach a screenshot of it here.

**Comment by RowanBee** [comment]
@IgnisDa Here is the collections page

![image](https://github.com/IgnisDa/ryot/assets/47164828/75f360d7-08b8-4a2f-8ed8-c583ce56fdaf)

**Comment by IgnisDa** [comment]
Keeping this open to add a fix to not be able to edit default collections.

**Comment by RowanBee** [comment]
Thank you. That being said, is there a way to bulk add to a collection? E.g. add all watched movies to one? Or is that a manual one-by-one process?

**Comment by IgnisDa** [comment]
No there isn't but you can use the gql api to do it.

`mediaSearch` query and add a filter for completed there. Then `addEntityToCollection` mutation.
