### ISSUE TITLE
HTTP error 200 when searching games (sometimes)

### ISSUE THREAD

**Issue by kaibagley** [IgnisDa/ryot#665]
Hey,

Every now and then when I search a game, I am shown a blank page with a "200" shown. Here is the docker logs:

```
[frontend] ClientError: invalid type: map, expected a sequence at line 1 column 0: {"response":{"data":null,"errors":[{"message":"invalid type: map, expected a sequence at line 1 column 0","locations":[{"line":2,"column":3}],"path":["mediaSearch"]}],"status":200,"headers":{}},"request":{"query":"query MediaSearch($lot: MetadataLot!, $source: MetadataSource!, $input: SearchInput!) {\n  mediaSearch(lot: $lot, source: $source, input: $input) {\n    details {\n      total\n      nextPage\n    }\n    items {\n      databaseId\n      hasInteracted\n      item {\n        identifier\n        title\n        image\n        publishYear\n      }\n    }\n  }\n}","variables":{"lot":"VIDEO_GAME","input":{"page":1,"query":"elden ring"},"source":"IGDB"}}}
[frontend]     at makeRequest (file:///home/ryot/node_modules/graphql-request/src/index.ts:426:11)
[frontend]     at processTicksAndRejections (node:internal/process/task_queues:95:5)
[frontend]     at file:///home/ryot/build/server/index.js?t=1709032867000:10463:43
[frontend]     at loader$d (file:///home/ryot/build/server/index.js?t=1709032867000:10432:36)
[frontend]     at Object.callRouteLoaderRR (/home/ryot/node_modules/@remix-run/server-runtime/dist/data.js:52:16)
[frontend]     at callLoaderOrAction (/home/ryot/node_modules/@remix-run/router/router.ts:4020:16)
[frontend]     at async Promise.all (index 0)
[frontend]     at loadRouteData (/home/ryot/node_modules/@remix-run/router/router.ts:3297:19)
[frontend]     at queryImpl (/home/ryot/node_modules/@remix-run/router/router.ts:3078:20)
[frontend]     at Object.queryRoute (/home/ryot/node_modules/@remix-run/router/router.ts:3018:18) {
[frontend]   response: {
[frontend]     data: null,
[frontend]     errors: [ [Object] ],
[frontend]     status: 200,
[frontend]     headers: Headers { [Symbol(map)]: [Object: null prototype] }
[frontend]   },
[frontend]   request: {
[frontend]     query: 'query MediaSearch($lot: MetadataLot!, $source: MetadataSource!, $input: SearchInput!) {\n' +
[frontend]       '  mediaSearch(lot: $lot, source: $source, input: $input) {\n' +
[frontend]       '    details {\n' +
[frontend]       '      total\n' +
[frontend]       '      nextPage\n' +
[frontend]       '    }\n' +
[frontend]       '    items {\n' +
[frontend]       '      databaseId\n' +
[frontend]       '      hasInteracted\n' +
[frontend]       '      item {\n' +
[frontend]       '        identifier\n' +
[frontend]       '        title\n' +
[frontend]       '        image\n' +
[frontend]       '        publishYear\n' +
[frontend]       '      }\n' +
[frontend]       '    }\n' +
[frontend]       '  }\n' +
[frontend]       '}',
[frontend]     variables: { lot: 'VIDEO_GAME', input: [Object], source: 'IGDB' }
[frontend]   }
[frontend] }
[frontend] GET /media/search/video_game?query=elden+ring&_data=routes%2F_dashboard.media.%24action.%24lot 500 - - 1325.417 ms
[frontend] ClientError: invalid type: map, expected a sequence at line 1 column 0: {"response":{"data":null,"errors":[{"message":"invalid type: map, expected a sequence at line 1 column 0","locations":[{"line":2,"column":3}],"path":["mediaSearch"]}],"status":200,"headers":{}},"request":{"query":"query MediaSearch($lot: MetadataLot!, $source: MetadataSource!, $input: SearchInput!) {\n  mediaSearch(lot: $lot, source: $source, input: $input) {\n    details {\n      total\n      nextPage\n    }\n    items {\n      databaseId\n      hasInteracted\n      item {\n        identifier\n        title\n        image\n        publishYear\n      }\n    }\n  }\n}","variables":{"lot":"VIDEO_GAME","input":{"page":1,"query":"elden "},"source":"IGDB"}}}
[frontend]     at makeRequest (file:///home/ryot/node_modules/graphql-request/src/index.ts:426:11)
[frontend]     at processTicksAndRejections (node:internal/process/task_queues:95:5)
[frontend]     at file:///home/ryot/build/server/index.js?t=1709032867000:10463:43
[frontend]     at loader$d (file:///home/ryot/build/server/index.js?t=1709032867000:10432:36)
[frontend]     at Object.callRouteLoaderRR (/home/ryot/node_modules/@remix-run/server-runtime/dist/data.js:52:16)
[frontend]     at callLoaderOrAction (/home/ryot/node_modules/@remix-run/router/router.ts:4020:16)
[frontend]     at async Promise.all (index 0)
[frontend]     at loadRouteData (/home/ryot/node_modules/@remix-run/router/router.ts:3297:19)
[frontend]     at queryImpl (/home/ryot/node_modules/@remix-run/router/router.ts:3078:20)
[frontend]     at Object.queryRoute (/home/ryot/node_modules/@remix-run/router/router.ts:3018:18) {
[frontend]   response: {
[frontend]     data: null,
[frontend]     errors: [ [Object] ],
[frontend]     status: 200,
[frontend]     headers: Headers { [Symbol(map)]: [Object: null prototype] }
[frontend]   },
[frontend]   request: {
[frontend]     query: 'query MediaSearch($lot: MetadataLot!, $source: MetadataSource!, $input: SearchInput!) {\n' +
[frontend]       '  mediaSearch(lot: $lot, source: $source, input: $input) {\n' +
[frontend]       '    details {\n' +
[frontend]       '      total\n' +
[frontend]       '      nextPage\n' +
[frontend]       '    }\n' +
[frontend]       '    items {\n' +
[frontend]       '      databaseId\n' +
[frontend]       '      hasInteracted\n' +
[frontend]       '      item {\n' +
[frontend]       '        identifier\n' +
[frontend]       '        title\n' +
[frontend]       '        image\n' +
[frontend]       '        publishYear\n' +
[frontend]       '      }\n' +
[frontend]       '    }\n' +
[frontend]       '  }\n' +
[frontend]       '}',
[frontend]     variables: { lot: 'VIDEO_GAME', input: [Object], source: 'IGDB' }
[frontend]   }
[frontend] }
[frontend] GET /media/search/video_game?query=elden+&_data=routes%2F_dashboard.media.%24action.%24lot 500 - - 1761.506 ms
[frontend] ClientError: invalid type: map, expected a sequence at line 1 column 0: {"response":{"data":null,"errors":[{"message":"invalid type: map, expected a sequence at line 1 column 0","locations":[{"line":2,"column":3}],"path":["mediaSearch"]}],"status":200,"headers":{}},"request":{"query":"query MediaSearch($lot: MetadataLot!, $source: MetadataSource!, $input: SearchInput!) {\n  mediaSearch(lot: $lot, source: $source, input: $input) {\n    details {\n      total\n      nextPage\n    }\n    items {\n      databaseId\n      hasInteracted\n      item {\n        identifier\n        title\n        image\n        publishYear\n      }\n    }\n  }\n}","variables":{"lot":"VIDEO_GAME","input":{"page":1,"query":"elden r"},"source":"IGDB"}}}
[frontend]     at makeRequest (file:///home/ryot/node_modules/graphql-request/src/index.ts:426:11)
[frontend]     at processTicksAndRejections (node:internal/process/task_queues:95:5)
[frontend]     at file:///home/ryot/build/server/index.js?t=1709032867000:10463:43
[frontend]     at loader$d (file:///home/ryot/build/server/index.js?t=1709032867000:10432:36)
[frontend]     at Object.callRouteLoaderRR (/home/ryot/node_modules/@remix-run/server-runtime/dist/data.js:52:16)
[frontend]     at callLoaderOrAction (/home/ryot/node_modules/@remix-run/router/router.ts:4020:16)
[frontend]     at async Promise.all (index 0)
[frontend]     at loadRouteData (/home/ryot/node_modules/@remix-run/router/router.ts:3297:19)
[frontend]     at queryImpl (/home/ryot/node_modules/@remix-run/router/router.ts:3078:20)
[frontend]     at Object.queryRoute (/home/ryot/node_modules/@remix-run/router/router.ts:3018:18) {
[frontend]   response: {
[frontend]     data: null,
[frontend]     errors: [ [Object] ],
[frontend]     status: 200,
[frontend]     headers: Headers { [Symbol(map)]: [Object: null prototype] }
[frontend]   },
[frontend]   request: {
[frontend]     query: 'query MediaSearch($lot: MetadataLot!, $source: MetadataSource!, $input: SearchInput!) {\n' +
[frontend]       '  mediaSearch(lot: $lot, source: $source, input: $input) {\n' +
[frontend]       '    details {\n' +
[frontend]       '      total\n' +
[frontend]       '      nextPage\n' +
[frontend]       '    }\n' +
[frontend]       '    items {\n' +
[frontend]       '      databaseId\n' +
[frontend]       '      hasInteracted\n' +
[frontend]       '      item {\n' +
[frontend]       '        identifier\n' +
[frontend]       '        title\n' +
[frontend]       '        image\n' +
[frontend]       '        publishYear\n' +
[frontend]       '      }\n' +
[frontend]       '    }\n' +
[frontend]       '  }\n' +
[frontend]       '}',
[frontend]     variables: { lot: 'VIDEO_GAME', input: [Object], source: 'IGDB' }
[frontend]   }
[frontend] }
[frontend] GET /media/search/video_game?query=elden+r&_data=routes%2F_dashboard.media.%24action.%24lot 500 - - 1722.166 ms
[frontend] ClientError: invalid type: map, expected a sequence at line 1 column 0: {"response":{"data":null,"errors":[{"message":"invalid type: map, expected a sequence at line 1 column 0","locations":[{"line":2,"column":3}],"path":["mediaSearch"]}],"status":200,"headers":{}},"request":{"query":"query MediaSearch($lot: MetadataLot!, $source: MetadataSource!, $input: SearchInput!) {\n  mediaSearch(lot: $lot, source: $source, input: $input) {\n    details {\n      total\n      nextPage\n    }\n    items {\n      databaseId\n      hasInteracted\n      item {\n        identifier\n        title\n        image\n        publishYear\n      }\n    }\n  }\n}","variables":{"lot":"VIDEO_GAME","input":{"page":1,"query":"elden rin"},"source":"IGDB"}}}
[frontend]     at makeRequest (file:///home/ryot/node_modules/graphql-request/src/index.ts:426:11)
[frontend]     at processTicksAndRejections (node:internal/process/task_queues:95:5)
[frontend]     at file:///home/ryot/build/server/index.js?t=1709032867000:10463:43
[frontend]     at loader$d (file:///home/ryot/build/server/index.js?t=1709032867000:10432:36)
[frontend]     at Object.callRouteLoaderRR (/home/ryot/node_modules/@remix-run/server-runtime/dist/data.js:52:16)
[frontend]     at callLoaderOrAction (/home/ryot/node_modules/@remix-run/router/router.ts:4020:16)
[frontend]     at async Promise.all (index 0)
[frontend]     at loadRouteData (/home/ryot/node_modules/@remix-run/router/router.ts:3297:19)
[frontend]     at queryImpl (/home/ryot/node_modules/@remix-run/router/router.ts:3078:20)
[frontend]     at Object.queryRoute (/home/ryot/node_modules/@remix-run/router/router.ts:3018:18) {
[frontend]   response: {
[frontend]     data: null,
[frontend]     errors: [ [Object] ],
[frontend]     status: 200,
[frontend]     headers: Headers { [Symbol(map)]: [Object: null prototype] }
[frontend]   },
[frontend]   request: {
[frontend]     query: 'query MediaSearch($lot: MetadataLot!, $source: MetadataSource!, $input: SearchInput!) {\n' +
[frontend]       '  mediaSearch(lot: $lot, source: $source, input: $input) {\n' +
[frontend]       '    details {\n' +
[frontend]       '      total\n' +
[frontend]       '      nextPage\n' +
[frontend]       '    }\n' +
[frontend]       '    items {\n' +
[frontend]       '      databaseId\n' +
[frontend]       '      hasInteracted\n' +
[frontend]       '      item {\n' +
[frontend]       '        identifier\n' +
[frontend]       '        title\n' +
[frontend]       '        image\n' +
[frontend]       '        publishYear\n' +
[frontend]       '      }\n' +
[frontend]       '    }\n' +
[frontend]       '  }\n' +
[frontend]       '}',
[frontend]     variables: { lot: 'VIDEO_GAME', input: [Object], source: 'IGDB' }
[frontend]   }
[frontend] }
[frontend] GET /media/search/video_game?query=elden+rin&_data=routes%2F_dashboard.media.%24action.%24lot 500 - - 1666.202 ms
```

Thanks for any help!

**Comment by IgnisDa** [comment]
Alright, will take a look. Thanks for reporting.

**Comment by IgnisDa** [comment]
@kaibagley I am not able to reproduce this. Can you record a video on it happening?

**Comment by kaibagley** [comment]
This is on the mobile web app, but it's the exact same on desktop too.

https://github.com/IgnisDa/ryot/assets/53884957/0f8a006d-28d5-491a-a286-fc04b1af9e46
