### ISSUE TITLE
Application error when importing JSON

### ISSUE THREAD

**Issue by Kwbmm** [IgnisDa/ryot#718]
Just tried to import the following media JSON:

```json
{
    "collections": [], 
    "identifier": "1705",
    "lot": "Show",
    "reviews": [],
    "source": "Tmdb",
    "source_id": "1705",
    "seen_history": [{
        "progress": 100,
        "show_episode_number": 1,
        "show_episode_series": 1,
        "ended_on": "2024-03-16T00:00:00.000Z",
        "started_on": "2024-03-16T00:00:00.000Z"
    }]
}
```

Got application error on the UI.

This on the logs:

```
ryot     | [frontend] FetchError: request to http://localhost:5000/graphql failed, reason: socket hang up
ryot     | [frontend]     at ClientRequest.<anonymous> (/home/ryot/node_modules/node-fetch/lib/index.js:1491:11)
ryot     | [frontend]     at ClientRequest.emit (node:events:514:28)
ryot     | [frontend]     at Socket.socketOnEnd (node:_http_client:519:9)
ryot     | [frontend]     at Socket.emit (node:events:526:35)
ryot     | [frontend]     at endReadableNT (node:internal/streams/readable:1589:12)
ryot     | [frontend]     at processTicksAndRejections (node:internal/process/task_queues:82:21) {
ryot     | [frontend]   type: 'system',
ryot     | [frontend]   errno: 'ECONNRESET',
ryot     | [frontend]   code: 'ECONNRESET'
ryot     | [frontend] }
ryot     | [frontend] POST /settings/imports-and-exports?intent=deployImport&_data=routes%2F_dashboard.settings.imports-and-exports._index 500 - - 67.006 ms
ryot     | [frontend] GET /settings/imports-and-exports 200 - - 58.296 ms
ryot     | [frontend] FetchError: request to http://localhost:5000/graphql failed, reason: socket hang up
ryot     | [frontend]     at ClientRequest.<anonymous> (/home/ryot/node_modules/node-fetch/lib/index.js:1491:11)
ryot     | [frontend]     at ClientRequest.emit (node:events:514:28)
ryot     | [frontend]     at Socket.socketOnEnd (node:_http_client:519:9)
ryot     | [frontend]     at Socket.emit (node:events:526:35)
ryot     | [frontend]     at endReadableNT (node:internal/streams/readable:1589:12)
ryot     | [frontend]     at processTicksAndRejections (node:internal/process/task_queues:82:21) {
ryot     | [frontend]   type: 'system',
ryot     | [frontend]   errno: 'ECONNRESET',
ryot     | [frontend]   code: 'ECONNRESET'
ryot     | [frontend] }
ryot     | [frontend] POST /settings/imports-and-exports?intent=deployImport&_data=routes%2F_dashboard.settings.imports-and-exports._index 500 - - 29.056 ms
ryot     | [frontend] GET /settings/imports-and-exports 200 - - 67.143 ms
ryot     | [frontend] Error: No route matches URL "/graphql"
ryot     | [frontend]     at getInternalRouterError (/home/ryot/node_modules/@remix-run/router/router.ts:4519:5)
ryot     | [frontend]     at Object.query (/home/ryot/node_modules/@remix-run/router/router.ts:2958:19)
ryot     | [frontend]     at handleDocumentRequestRR (/home/ryot/node_modules/@remix-run/server-runtime/dist/server.js:184:35)
ryot     | [frontend]     at requestHandler (/home/ryot/node_modules/@remix-run/server-runtime/dist/server.js:108:24)
ryot     | [frontend]     at /home/ryot/node_modules/@remix-run/express/dist/server.js:41:28
ryot     | [frontend] ErrorResponseImpl {
ryot     | [frontend]   status: 404,
ryot     | [frontend]   statusText: 'Not Found',
ryot     | [frontend]   internal: true,
ryot     | [frontend]   data: 'Error: No route matches URL "/graphql"',
ryot     | [frontend]   error: Error: No route matches URL "/graphql"
ryot     | [frontend]       at getInternalRouterError (/home/ryot/node_modules/@remix-run/router/router.ts:4519:5)
ryot     | [frontend]       at Object.query (/home/ryot/node_modules/@remix-run/router/router.ts:2958:19)
ryot     | [frontend]       at handleDocumentRequestRR (/home/ryot/node_modules/@remix-run/server-runtime/dist/server.js:184:35)
ryot     | [frontend]       at requestHandler (/home/ryot/node_modules/@remix-run/server-runtime/dist/server.js:108:24)
ryot     | [frontend]       at /home/ryot/node_modules/@remix-run/express/dist/server.js:41:28
ryot     | [frontend] }
ryot     | [frontend] GET /graphql 404 - - 73.653 ms
ryot     | [frontend] Error: No route matches URL "/favicon.ico"
ryot     | [frontend]     at getInternalRouterError (/home/ryot/node_modules/@remix-run/router/router.ts:4519:5)
ryot     | [frontend]     at Object.query (/home/ryot/node_modules/@remix-run/router/router.ts:2958:19)
ryot     | [frontend]     at handleDocumentRequestRR (/home/ryot/node_modules/@remix-run/server-runtime/dist/server.js:184:35)
ryot     | [frontend]     at requestHandler (/home/ryot/node_modules/@remix-run/server-runtime/dist/server.js:108:24)
ryot     | [frontend]     at /home/ryot/node_modules/@remix-run/express/dist/server.js:41:28
ryot     | [frontend] ErrorResponseImpl {
ryot     | [frontend]   status: 404,
ryot     | [frontend]   statusText: 'Not Found',
ryot     | [frontend]   internal: true,
ryot     | [frontend]   data: 'Error: No route matches URL "/favicon.ico"',
ryot     | [frontend]   error: Error: No route matches URL "/favicon.ico"
ryot     | [frontend]       at getInternalRouterError (/home/ryot/node_modules/@remix-run/router/router.ts:4519:5)
ryot     | [frontend]       at Object.query (/home/ryot/node_modules/@remix-run/router/router.ts:2958:19)
ryot     | [frontend]       at handleDocumentRequestRR (/home/ryot/node_modules/@remix-run/server-runtime/dist/server.js:184:35)
ryot     | [frontend]       at requestHandler (/home/ryot/node_modules/@remix-run/server-runtime/dist/server.js:108:24)
ryot     | [frontend]       at /home/ryot/node_modules/@remix-run/express/dist/server.js:41:28
ryot     | [frontend] }
ryot     | [frontend] GET /favicon.ico 404 - - 7.192 ms
ryot     | [frontend] FetchError: request to http://localhost:5000/graphql failed, reason: socket hang up
ryot     | [frontend]     at ClientRequest.<anonymous> (/home/ryot/node_modules/node-fetch/lib/index.js:1491:11)
ryot     | [frontend]     at ClientRequest.emit (node:events:514:28)
ryot     | [frontend]     at Socket.socketOnEnd (node:_http_client:519:9)
ryot     | [frontend]     at Socket.emit (node:events:526:35)
ryot     | [frontend]     at endReadableNT (node:internal/streams/readable:1589:12)
ryot     | [frontend]     at processTicksAndRejections (node:internal/process/task_queues:82:21) {
ryot     | [frontend]   type: 'system',
ryot     | [frontend]   errno: 'ECONNRESET',
ryot     | [frontend]   code: 'ECONNRESET'
ryot     | [frontend] }
ryot     | [frontend] POST /settings/imports-and-exports?intent=deployImport&_data=routes%2F_dashboard.settings.imports-and-exports._index 500 - - 11.582 ms
ryot     | [frontend] GET /?_data=root 200 - - 3.019 ms
ryot     | [frontend] GET /?_data=routes%2F_dashboard._index 200 - - 60.201 ms
```

**Comment by IgnisDa** [comment]
@Kwbmm It should be `show_season_number` not `show_episode_series`. There is some other bug too. I will look into it.

**Comment by IgnisDa** [comment]
THe format should be as follows:
```json
[
 { 
    "collections": [],
    "identifier": "1705",
    "lot": "Show",
    "reviews": [],
    "source": "Tmdb",
    "source_id": "1705",
    "seen_history": [{
        "progress": 100,
        "show_episode_number": 1,
        "show_season_number": 1,
        "ended_on": "2024-03-16T00:00:00.000Z",
        "started_on": "2024-03-16T00:00:00.000Z"
    }]
  }
]
```

**Comment by Kwbmm** [comment]
Just tried importing the file adjusted according to your indications. Still get application error:

```

ryot  | [frontend] GET /settings/imports-and-exports?_data=routes%2F_dashboard.settings.imports-and-exports._index 200 - - 25.824 ms
ryot  | [frontend] FetchError: request to http://localhost:5000/graphql failed, reason: socket hang up
ryot  | [frontend]     at ClientRequest.<anonymous> (/home/ryot/node_modules/node-fetch/lib/index.js:1491:11)
ryot  | [frontend]     at ClientRequest.emit (node:events:514:28)
ryot  | [frontend]     at Socket.socketOnEnd (node:_http_client:519:9)
ryot  | [frontend]     at Socket.emit (node:events:526:35)
ryot  | [frontend]     at endReadableNT (node:internal/streams/readable:1589:12)
ryot  | [frontend]     at processTicksAndRejections (node:internal/process/task_queues:82:21) {
ryot  | [frontend]   type: 'system',
ryot  | [frontend]   errno: 'ECONNRESET',
ryot  | [frontend]   code: 'ECONNRESET'
ryot  | [frontend] }
ryot  | [frontend] POST /settings/imports-and-exports?intent=deployImport&_data=routes%2F_dashboard.settings.imports-and-exports._index 500 - - 55.724 ms
```

**Comment by IgnisDa** [comment]
How are you importing it? I would appreciate it if you could show me a video or something of the bug.

**Comment by Kwbmm** [comment]
I don't do anything peculiar.

I go to settings -> Import and Export -> import media json -> select the file (the one you've given me [here](https://github.com/IgnisDa/ryot/issues/718#issuecomment-2019205504) and click import. And I get this:

Before import:
![image](https://github.com/IgnisDa/ryot/assets/8115374/155c438b-a511-4bfb-90ac-b456b616c625)

Result:
![image](https://github.com/IgnisDa/ryot/assets/8115374/a3738a23-710a-4f49-81bb-07590a9a8848)

The request that errors is the following:
`POST https://<base_url_redacted>/settings/imports-and-exports?intent=deployImport&_data=routes/_dashboard.settings.imports-and-exports._index`

Payload
 ```
-----------------------------548894736079352452197645719
Content-Disposition: form-data; name="source"

MEDIA_JSON
-----------------------------548894736079352452197645719
Content-Disposition: form-data; name="export"; filename="ryot_data.json"
Content-Type: application/json

[
    { 
       "collections": [],
       "identifier": "1705",
       "lot": "Show",
       "reviews": [],
       "source": "Tmdb",
       "source_id": "1705",
       "seen_history": [{
           "progress": 100,
           "show_episode_number": 1,
           "show_season_number": 1,
           "ended_on": "2024-03-16T00:00:00.000Z",
           "started_on": "2024-03-16T00:00:00.000Z"
       }]
    }
]
-----------------------------548894736079352452197645719--
```

Response: `{"message":"Unexpected Server Error"}`

**Comment by IgnisDa** [comment]
What do the backend logs say?

**Comment by Kwbmm** [comment]
```

ryot  | [frontend] GET /settings/imports-and-exports?_data=routes%2F_dashboard.settings.imports-and-exports._index 200 - - 30.634 ms
ryot  | [frontend] FetchError: request to http://localhost:5000/graphql failed, reason: socket hang up
ryot  | [frontend]     at ClientRequest.<anonymous> (/home/ryot/node_modules/node-fetch/lib/index.js:1491:11)
ryot  | [frontend]     at ClientRequest.emit (node:events:514:28)
ryot  | [frontend]     at Socket.socketOnEnd (node:_http_client:519:9)
ryot  | [frontend]     at Socket.emit (node:events:526:35)
ryot  | [frontend]     at endReadableNT (node:internal/streams/readable:1589:12)
ryot  | [frontend]     at processTicksAndRejections (node:internal/process/task_queues:82:21) {
ryot  | [frontend]   type: 'system',
ryot  | [frontend]   errno: 'ECONNRESET',
ryot  | [frontend]   code: 'ECONNRESET'
ryot  | [frontend] }
ryot  | [frontend] POST /settings/imports-and-exports?intent=deployImport&_data=routes%2F_dashboard.settings.imports-and-exports._index 500 - - 63.230 ms
```

This is all I have in the logs

**Comment by Kwbmm** [comment]
I don't know if it's relevant, but Ryot is running behind a Traefik reverse proxy

**Comment by IgnisDa** [comment]
Please share your docker compose.

**Comment by Kwbmm** [comment]
You can find it here: https://github.com/Kwbmm/Homeserver/tree/master

In the root folder, there's the main compose file, docker-compose.yml

In the compose folder there's the ryot compose config.

My ryot instance is exposed to the Internet

**Comment by Kwbmm** [comment]
I will try to run a ryot outside of traefik and see if the errors persists, at least to try and rule out something.

Does the media import works for you?

**Comment by IgnisDa** [comment]
Yep the import works fine for me. I suggest you go ahead without traefik setup. That will allow us to isolate whether the problem is with Ryot or Traefik.

The last time someone brought up Traefik problems, the solution was removing the healthcheck from the Ryot dockerfile. I had added a healthcheck for every 5 minutes, but Traefik was considering the application unhealthy for 5 minutes. Removing the `HEALTHCHECK` directive fixed that.

**Comment by Kwbmm** [comment]
Tried with a local docker compose, no traefik. Log below, as usual, same error.

```
ryot     | [frontend] FetchError: request to http://localhost:5000/graphql failed, reason: socket hang up
ryot     | [frontend]     at ClientRequest.<anonymous> (/home/ryot/node_modules/node-fetch/lib/index.js:1491:11)
ryot     | [frontend]     at ClientRequest.emit (node:events:514:28)
ryot     | [frontend]     at Socket.socketOnEnd (node:_http_client:519:9)
ryot     | [frontend]     at Socket.emit (node:events:526:35)
ryot     | [frontend]     at endReadableNT (node:internal/streams/readable:1589:12)
ryot     | [frontend]     at processTicksAndRejections (node:internal/process/task_queues:82:21) {
ryot     | [frontend]   type: 'system',
ryot     | [frontend]   errno: 'ECONNRESET',
ryot     | [frontend]   code: 'ECONNRESET'
ryot     | [frontend] }
```

> Yep the import works fine for me.

I don't know what you tested, but the import is broken

**Comment by Kwbmm** [comment]
Can you try to import the following in a docker compose setup?

```
[
 { 
    "collections": [],
    "identifier": "1705",
    "lot": "Show",
    "reviews": [],
    "source": "Tmdb",
    "source_id": "1705",
    "seen_history": [{
        "progress": 100,
        "show_episode_number": 1,
        "show_season_number": 1,
        "ended_on": "2024-03-16T00:00:00.000Z",
        "started_on": "2024-03-16T00:00:00.000Z"
    }]
  }
]
```

**Comment by IgnisDa** [comment]
Yep it works fine for me.

When you start the container, does the backend start up?

**Comment by Kwbmm** [comment]
I think so?

This is the startup log:

```
ryot-db  | 
ryot-db  | PostgreSQL Database directory appears to contain a database; Skipping initialization
ryot-db  | 
ryot-db  | 2024-03-31 17:05:46.438 UTC [1] LOG:  starting PostgreSQL 16.2 on x86_64-pc-linux-musl, compiled by gcc (Alpine 13.2.1_git20231014) 13.2.1 20231014, 64-bit
ryot-db  | 2024-03-31 17:05:46.438 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
ryot-db  | 2024-03-31 17:05:46.438 UTC [1] LOG:  listening on IPv6 address "::", port 5432
ryot-db  | 2024-03-31 17:05:46.460 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
ryot-db  | 2024-03-31 17:05:46.492 UTC [24] LOG:  database system was shut down at 2024-03-31 14:01:21 UTC
ryot-db  | 2024-03-31 17:05:46.536 UTC [1] LOG:  database system is ready to accept connections
ryot     | [backend] 2024-03-31T17:05:46.968036Z  INFO ryot: Running version: 4.3.13
ryot     | [backend] 2024-03-31T17:05:47.108891Z  INFO sea_orm_migration::migrator: Applying all pending migrations
ryot     | [backend] 2024-03-31T17:05:47.130255Z  INFO sea_orm_migration::migrator: No pending migrations
ryot     | [proxy] {"level":"info","ts":1711904747.1386662,"msg":"using provided configuration","config_file":"/etc/caddy/Caddyfile","config_adapter":""}
ryot     | [proxy] {"level":"warn","ts":1711904747.1415868,"logger":"admin","msg":"admin endpoint disabled"}
ryot     | [proxy] {"level":"warn","ts":1711904747.141987,"logger":"http.auto_https","msg":"automatic HTTPS is completely disabled for server","server_name":"srv0"}
ryot     | [proxy] {"level":"info","ts":1711904747.142609,"logger":"tls.cache.maintenance","msg":"started background certificate maintenance","cache":"0xc000117a00"}
ryot     | [proxy] {"level":"info","ts":1711904747.143866,"logger":"tls","msg":"cleaning storage unit","description":"FileStorage:/home/ryot/.local/share/caddy"}
ryot     | [backend] 2024-03-31T17:05:47.144388Z  INFO ryot: Using timezone: Etc/GMT
ryot     | [proxy] {"level":"info","ts":1711904747.1463592,"logger":"tls","msg":"finished cleaning storage units"}
ryot     | [proxy] {"level":"info","ts":1711904747.1470292,"logger":"http.log","msg":"server running","name":"srv0","protocols":["h1","h2","h3"]}
ryot     | [proxy] {"level":"info","ts":1711904747.1473002,"msg":"autosaved config (load with --resume flag)","file":"/home/ryot/.config/caddy/autosave.json"}
ryot     | [proxy] {"level":"info","ts":1711904747.1473129,"msg":"serving initial configuration"}
ryot     | [backend] 2024-03-31T17:05:47.173922Z  INFO ryot: Listening on: 0.0.0.0:5000
ryot     | [frontend] [remix-serve] http://localhost:3000 (http://172.24.0.3:3000)
```

**Comment by IgnisDa** [comment]
I don't think I know how to fix this. Is anything else breaking?

**Comment by Kwbmm** [comment]
Not like this, for what I've seen. Though I'm not using ryot much because everything goes through the possibility of importing my existing TVTime data into Ryot which, as of now, cannot do.

I've also used Ryot only for tv series tracking with the jellyfin integration: it needs improvements because the hook doesn't always work, but it's a minor problem compared to this.

**Comment by IgnisDa** [comment]
Try this:

```bash
docker exec -it ryot bash
curl -v http://localhost:5000/config
```

**Comment by Kwbmm** [comment]
Works

```
yot@f97b3549f400:~$ curl -v http://localhost:5000/config
*   Trying 127.0.0.1:5000...
* Connected to localhost (127.0.0.1) port 5000 (#0)
> GET /config HTTP/1.1
> Host: localhost:5000
> User-Agent: curl/7.88.1
> Accept: */*
> 
< HTTP/1.1 200 OK
< content-type: application/json
< content-length: 1480
< vary: origin, access-control-request-method, access-control-request-headers
< access-control-allow-credentials: true
< date: Tue, 02 Apr 2024 00:01:43 GMT
< 
{"anime_and_manga":{"anilist":{"prefer_english":false},"mal":{"client_id":"****"},"manga_updates":{}},"audio_books":{"audible":{"locale":"us"}},"books":{"openlibrary":{"cover_image_size":"M"},"google_books":{"pass_raw_query":false}},"database":{"url":"****"},"exercise":{},"file_storage":{"s3_access_key_id":"****","s3_bucket_name":"****","s3_region":"****","s3_secret_access_key":"****","s3_url":"****"},"frontend":{"url":"https://ryot.fly.dev","insecure_cookies":false,"item_details_height":300,"page_size":20,"umami":{"script_url":"","website_id":"","domains":""}},"integration":{"pull_every":2,"hasher_salt":"****","minimum_progress_limit":2,"maximum_progress_limit":95},"media":{},"movies_and_shows":{"tmdb":{"access_token":"****","locale":"en"}},"podcasts":{"listennotes":{"api_token":"****"},"itunes":{"locale":"en_us"}},"scheduler":{"database_url":"****","rate_limit_num":5,"user_cleanup_every":12},"server":{"smtp":{"server":"****","port":587,"user":"****","password":"****","mailbox":"****"},"config_dump_path":"*** Connection #0 to host localhost left intact
**","cors_origins":["****"],"progress_update_threshold":2,"person_outdated_threshold":30,"max_file_size":70,"graphql_playground_enabled":true,"disable_background_jobs":false},"users":{"jwt_secret":"****","allow_registration":true,"reviews_disabled":false,"token_valid_for_days":90,"validate_password":true},"video_games":{"igdb":{"image_size":"t_original"},"twitch":{"client_id":"****","client_secret":"****"}},"visual_novels":{},"disable_telemetry":false}ryot@f97b3549f400:~$ 
```

I think the problem lies in the import: the error maks me think of a fatal exception not caught either in rust or on gql side (not a rust expert so I don't even know if it's possible) that makes the backend crash (that would explain the `socket hung up` error).

Unfortunately I have 0 familiarity with the tech stack being used in this project, so can't really help more than giving you my feelings.

**Comment by Kwbmm** [comment]
But looking at the request it seems it's not even reaching graphql... So not sure

**Comment by IgnisDa** [comment]
No the request is going fine. It first goes to the remix action which is further supposed to send it to the graphql backend endpoint.

Anyways, I have been able to reproduce the error, though I have no idea about how to fix it. I will take a look into fixing it.

**Comment by IgnisDa** [comment]
@Kwbmm It should work now. Please upgrade.

**Comment by IgnisDa** [comment]
Hey @Kwbmm, were you able to import your Tvtime data into Ryot? A lot of users are asking me to write an importer, so if you can make a PR for this I'd be grateful. Otherwise, if possible, you can share the export files with me and I can write the implementation myself.

**Comment by Kwbmm** [comment]
I tested the import with the dummy file and it works :partying_face: 

I will attempt to run a full-ish migration of my data. 

I'll be making a repository for the script so that others can use it, but I don't believe I'll be able to complete it before I leave on holiday.

Given the data I received from TVTime, there's a lot to do in my opinion to writing a very good importer and, as of now, I'm doing this in my free time (I stopped working on it because I was not sure if you could fix the import).

**Comment by IgnisDa** [comment]
If you are willing to, you can email the files to me and then I can add it as an importer to Ryot itself.

Otherwise, a repository is fine too, though it would be community mantained.

**Comment by Kwbmm** [comment]
I redacted my personal data and made a repository here: https://github.com/Kwbmm/TVTime2Ryot

The script needs to be finished though
