### ISSUE TITLE
Error 500: Backend error

### ISSUE THREAD

**Issue by mrdev023** [IgnisDa/ryot#740]
I get the following error

```bash
backend] 2024-04-03T08:41:30.547892Z  INFO ryot: Running version: 4.3.16
[proxy] {"level":"info","ts":1712133690.5893466,"msg":"using provided configuration","config_file":"/etc/caddy/Caddyfile","config_adapter":""}
[proxy] {"level":"warn","ts":1712133690.5908196,"logger":"admin","msg":"admin endpoint disabled"}
[proxy] {"level":"warn","ts":1712133690.5909758,"logger":"http.auto_https","msg":"automatic HTTPS is completely disabled for server","server_name":"srv0"}
[proxy] {"level":"info","ts":1712133690.591048,"logger":"tls.cache.maintenance","msg":"started background certificate maintenance","cache":"0xc0004c9a80"}
[proxy] {"level":"info","ts":1712133690.591649,"logger":"http.log","msg":"server running","name":"srv0","protocols":["h1","h2","h3"]}
[proxy] {"level":"info","ts":1712133690.5916796,"logger":"tls","msg":"cleaning storage unit","description":"FileStorage:/home/ryot/.local/share/caddy"}
[proxy] {"level":"info","ts":1712133690.5917425,"logger":"tls","msg":"finished cleaning storage units"}
[proxy] {"level":"info","ts":1712133690.591936,"msg":"autosaved config (load with --resume flag)","file":"/home/ryot/.config/caddy/autosave.json"}
[proxy] {"level":"info","ts":1712133690.5919502,"msg":"serving initial configuration"}
[backend] 2024-04-03T08:41:30.597668Z  INFO sea_orm_migration::migrator: Applying all pending migrations
[backend] 2024-04-03T08:41:30.601887Z  INFO sea_orm_migration::migrator: No pending migrations
[backend] 2024-04-03T08:41:30.605172Z  INFO ryot: Using timezone: Etc/GMT
[backend] 2024-04-03T08:41:30.612356Z  INFO ryot: Listening on: 0.0.0.0:5000
[frontend] [remix-serve] http://localhost:3000 (http://192.168.64.3:3000)
[backend] thread 'tokio-runtime-worker' panicked at apps/backend/src/miscellaneous/resolver.rs:7002:48:
[backend] called `Option::unwrap()` on a `None` value
[backend] note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[proxy] {"level":"info","ts":1712220090.616059,"logger":"tls","msg":"cleaning storage unit","description":"FileStorage:/home/ryot/.local/share/caddy"}
[proxy] {"level":"info","ts":1712220090.6211622,"logger":"tls","msg":"finished cleaning storage units"}
[frontend] TypeError: Cannot read properties of undefined (reading 'collections')
[frontend]     at loader$2 (file:///home/ryot/build/server/index.js?t=1712132349000:13058:66)
[frontend]     at processTicksAndRejections (node:internal/process/task_queues:95:5)
[frontend]     at Object.callRouteLoaderRR (/home/ryot/node_modules/@remix-run/server-runtime/dist/data.js:52:16)
[frontend]     at callLoaderOrAction (/home/ryot/node_modules/@remix-run/router/router.ts:4043:16)
[frontend]     at async Promise.all (index 1)
[frontend]     at loadRouteData (/home/ryot/node_modules/@remix-run/router/router.ts:3320:19)
[frontend]     at queryImpl (/home/ryot/node_modules/@remix-run/router/router.ts:3101:20)
[frontend]     at Object.query (/home/ryot/node_modules/@remix-run/router/router.ts:2977:18)
[frontend]     at handleDocumentRequestRR (/home/ryot/node_modules/@remix-run/server-runtime/dist/server.js:184:15)
[frontend]     at requestHandler (/home/ryot/node_modules/@remix-run/server-runtime/dist/server.js:108:18)
```

https://github.com/IgnisDa/ryot/blob/v4.3.16/apps/backend/src/miscellaneous/resolver.rs#L7002

**Comment by NoxRare** [comment]
I'm getting this error aswell, I updated the docker container and didnt change anything else..

**Comment by IgnisDa** [comment]
Clear your cookies and login again.
