### ISSUE TITLE
[error] TypeError: Cannot read properties of undefined (reading 'collections')

### ISSUE THREAD

**Issue by edersong** [IgnisDa/ryot#754]
Upgraded the containers and Ryot stopped to work reporting the following error:
```
[frontend] [remix-serve] http://localhost:3000 (http://192.168.0.2:3000)
[frontend] TypeError: Cannot read properties of undefined (reading 'collections')
[frontend]     at loader$2 (file:///home/ryot/build/server/index.js?t=1712589938000:13081:66)
[frontend]     at processTicksAndRejections (node:internal/process/task_queues:95:5)
[frontend]     at Object.callRouteLoaderRR (/home/ryot/node_modules/@remix-run/server-runtime/dist/data.js:52:16)
[frontend]     at callLoaderOrAction (/home/ryot/node_modules/@remix-run/router/router.ts:4043:16)
[frontend]     at async Promise.all (index 1)
[frontend]     at loadRouteData (/home/ryot/node_modules/@remix-run/router/router.ts:3320:19)
[frontend]     at queryImpl (/home/ryot/node_modules/@remix-run/router/router.ts:3101:20)
[frontend]     at Object.query (/home/ryot/node_modules/@remix-run/router/router.ts:2977:18)
[frontend]     at handleDocumentRequestRR (/home/ryot/node_modules/@remix-run/server-runtime/dist/server.js:184:15)
[frontend]     at requestHandler (/home/ryot/node_modules/@remix-run/server-runtime/dist/server.js:108:18)
[frontend] [Error: Unexpected Server Error]
[frontend] GET / 500 - - 937.570 ms
```

**Comment by IgnisDa** [comment]
Clear your cookies and login again.
