### ISSUE TITLE
Application Error while searching for a new show

### ISSUE THREAD

**Issue by Oosmus** [IgnisDa/ryot#766]
Hey there! I'm attempting to get into habit of using this and went to setup my plex integration. When I went to add shows to my watchlist the app would crash upon attempting to search. Here are the logs below.

> [frontend]     at callLoaderOrAction (/home/ryot/node_modules/@remix-run/router/router.ts:4043:16)
[frontend]     at async Promise.all (index 0)
[frontend]     at loadRouteData (/home/ryot/node_modules/@remix-run/router/router.ts:3320:19)
[frontend]     at queryImpl (/home/ryot/node_modules/@remix-run/router/router.ts:3101:20)
[frontend]     at Object.queryRoute (/home/ryot/node_modules/@remix-run/router/router.ts:3041:18) {
[frontend]   response: {
[frontend]     error: 'Service panicked',
[frontend]     status: 500,
[frontend]     headers: Headers { [Symbol(map)]: [Object: null prototype] }
[frontend]   },
[frontend]   request: {
[frontend]     query: 'query MetadataSearch($input: MetadataSearchInput!) {\n' +
[frontend]       '  metadataSearch(input: $input) {\n' +
[frontend]       '    details {\n' +
[frontend]       '      total\n' +
[frontend]       '      nextPage\n' +
[frontend]       '    }\n' +
[frontend]       '    items {\n' +
[frontend]       '      databaseId\n' +
[frontend]       '      hasInteracted\n' +
[frontend]       '      item {\n' +
[frontend]       '        identifier\n' +
[frontend]       '        title\n' +
[frontend]       '        image\n' +
[frontend]       '        publishYear\n' +
[frontend]       '      }\n' +
[frontend]       '    }\n' +
[frontend]       '  }\n' +
[frontend]       '}',
[frontend]     variables: { input: [Object] }
[frontend]   }
[frontend] }

**Comment by IgnisDa** [comment]
Please attach a bigger section of your logs so that I can see what exactly panicked in the backend.

**Comment by IgnisDa** [comment]
Closing due to inactivity. Feel free to ping me here if you need help.
