### ISSUE TITLE
[Bug] Using filter results in HTTP 500 status

### ISSUE THREAD

**Issue by hollowdew** [IgnisDa/ryot#784]
Hello,

I am using the latest docker version of ryot with postgresql.
When I go to Media -> Animes and click on the filter icon and select "Completed" 

> http://localhost:8081/media/list/anime?generalFilter=COMPLETED

the frontend says:

> We encountered an error. If you recently upgraded the server, you may have to logout and login again. If the error still persists, please create a new issue on [GitHub](https://github.com/ignisda/ryot/issues).

I configured ryot with the environment variable **RUST_BACKTRACE=full**.
These are the logs from ryot:

```
[backend] thread 'tokio-runtime-worker' panicked at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/sqlx-postgres-0.7.4/src/message/parse.rs:31:13:
[backend] assertion failed: self.param_types.len() <= (u16::MAX as usize)
[backend] stack backtrace:
[backend]    0:     0x55c28aedb376 - std::backtrace_rs::backtrace::libunwind::trace::hd6ffdc229294c06f
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/../../backtrace/src/backtrace/libunwind.rs:104:5
[backend]    1:     0x55c28aedb376 - std::backtrace_rs::backtrace::trace_unsynchronized::h991f79b6e9960513
[backend]                                at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
[backend]    2:     0x55c28aedb376 - std::sys_common::backtrace::_print_fmt::hf4ebe716f7ccda10
[backend]                                at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/sys_common/backtrace.rs:68:5
[backend]    3:     0x55c28aedb376 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h410d4c66be4e37f9
[backend]                                at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/sys_common/backtrace.rs:44:22
[backend]    4:     0x55c28af090f0 - core::fmt::rt::Argument::fmt::he0ff0e0e188c0db5
[backend]                                at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/core/src/fmt/rt.rs:142:9
[backend]    5:     0x55c28af090f0 - core::fmt::write::he40921d4802ce2ac
[backend]                                at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/core/src/fmt/mod.rs:1120:17
   6:     0x55c28aed74bf - std::io::Write::write_fmt::h5de5a4e7037c9b20
[backend]                                at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/io/mod.rs:1846:15
[backend]    7:     0x55c28aedb154 - std::sys_common::backtrace::_print::hd8e2e3f655086663
[backend]                                at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/sys_common/backtrace.rs:47:5
[backend]    8:     0x55c28aedb154 - std::sys_common::backtrace::print::h11c067a88e3bdb22
[backend]                                at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/sys_common/backtrace.rs:34:9
[backend]    9:     0x55c28aedc9d7 - std::panicking::default_hook::{{closure}}::h8c832ecb03fde8ea
[backend]   10:     0x55c28aedc739 - std::panicking::default_hook::h1633e272b4150cf3
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/panicking.rs:292:9
[backend]   11:     0x55c28aedce68 - std::panicking::rust_panic_with_hook::hb164d19c0c1e71d4
[backend]                                at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/panicking.rs:781:13
[backend]   12:     0x55c28aedcd09 - std::panicking::begin_panic_handler::{{closure}}::h0369088c533c20e9
[backend]                                at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/panicking.rs:651:13
[backend]   13:     0x55c28aedb876 - std::sys_common::backtrace::__rust_end_short_backtrace::hc11d910daf35ac2e
[backend]                                at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/sys_common/backtrace.rs:171:18
[backend]   14:     0x55c28aedca94 - rust_begin_unwind
[backend]                                at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/panicking.rs:647:5
  15:     0x55c288817365 - core::panicking::panic_fmt::ha6effc2775a0749c
[backend]                                at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/core/src/panicking.rs:72:14
[backend]   16:     0x55c288817423 - core::panicking::panic::h44790a89027c670f
[backend]                                at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/core/src/panicking.rs:144:5
[backend]   17:     0x55c28ad2b012 - <alloc::vec::Vec<u8> as sqlx_postgres::io::buf_mut::PgBufMutExt>::put_length_prefixed::h029452abb6e1fd2d
[backend]   18:     0x55c28a41db2c - sqlx_core::net::socket::buffered::BufferedSocket<S>::write::he6ec1370421e781b
[backend]   19:     0x55c28a4363ad - sqlx_postgres::connection::executor::<impl sqlx_postgres::connection::PgConnection>::run::{{closure}}::h2628f71f83824381
[backend]   20:     0x55c28a4341a1 - sqlx_postgres::connection::executor::<impl sqlx_core::executor::Executor for &mut sqlx_postgres::connection::PgConnection>::fetch_optional::{{closure}}::h632ed1d001206308
  21:     0x55c28a44ce0a - <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll::h98a8edc2068bfc8c
[backend]   22:     0x55c28a44d2a8 - <futures_util::future::try_future::try_flatten::TryFlatten<Fut,<Fut as futures_core::future::TryFuture>::Ok> as core::future::future::Future>::poll::h5478aa82c36847a1
[backend]   23:     0x55c28a4226f9 - <futures_util::future::try_future::AndThen<Fut1,Fut2,F> as core::future::future::Future>::poll::h0d2a77d453fba00c
[backend]   24:     0x55c28a4457cb - <sea_orm::database::db_connection::DatabaseConnection as sea_orm::database::connection::ConnectionTrait>::query_one::{{closure}}::hc302fd13d8a0751d
[backend]   25:     0x55c288d2228a - ryot::miscellaneous::resolver::MiscellaneousService::metadata_list::{{closure}}::hb6c27ca1137d810e
[backend]   26:     0x55c288daa7a8 - ryot::miscellaneous::resolver::_::<impl async_graphql::resolver_utils::container::ContainerType for ryot::miscellaneous::resolver::MiscellaneousQuery>::resolve_field::{{closure}}::heb1b27b1700be06d
[backend]   27:     0x55c288baf5a0 - <async_graphql::types::query_root::QueryRoot<T> as async_graphql::resolver_utils::container::ContainerType>::resolve_field::{{closure}}::h3891f670c3fbb315
[backend]   28:     0x55c288cb551c - <core::pin::Pin<P> as core::future::future::Future>::poll::ha71ad1726b955f38
[backend]   29:     0x55c28a639458 - async_graphql::extensions::NextResolve::run::{{closure}}::h1d08975c56de871f
[backend]   30:     0x55c28a635ad6 - <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll::hfe40f4c654edf9ab
[backend]   31:     0x55c28a630670 - <async_graphql::extensions::tracing::TracingExtension as async_graphql::extensions::Extension>::resolve::{{closure}}::h716d375f74d4ebf5
[backend]   32:     0x55c28881fea2 - async_graphql::extensions::Extensions::resolve::{{closure}}::he9f9f93e34e40d7e
[backend]   33:     0x55c28898a138 - async_graphql::resolver_utils::container::Fields::add_set::{{closure}}::hc66b6ada850385a3
[backend]   34:     0x55c28945aed4 - <futures_util::future::try_maybe_done::TryMaybeDone<Fut> as core::future::future::Future>::poll::hb358f24399a660df
[backend]   35:     0x55c2899252e8 - <futures_util::future::try_join_all::TryJoinAll<F> as core::future::future::Future>::poll::h3e662cd7465a9f1a
[backend]   36:     0x55c2893836ef - async_graphql::schema::Schema<Query,Mutation,Subscription>::execute::{{closure}}::{{closure}}::{{closure}}::{{closure}}::hec428f2624c33eaa
[backend]   37:     0x55c28a62f8f0 - <async_graphql::extensions::tracing::TracingExtension as async_graphql::extensions::Extension>::execute::{{closure}}::h9943545ff6c20bdc
[backend]   38:     0x55c288c3c6d3 - <core::pin::Pin<P> as core::future::future::Future>::poll::h0d2f84726bb4a101
[backend]   39:     0x55c28a62d7fb - <async_graphql::extensions::tracing::TracingExtension as async_graphql::extensions::Extension>::request::{{closure}}::h1fdd344480ba88e1
[backend]   40:     0x55c289c43a99 - <F as axum::handler::Handler<(M,T1,T2,T3),S>>::call::{{closure}}::h4f8da028add9adf8
[backend]   41:     0x55c289716d04 - <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll::h43076fa9d719a4c7
  42:     0x55c2897189ba - <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll::h84eba9582c6ea73d
[backend]   43:     0x55c28921c3e9 - <tower::util::map_response::MapResponseFuture<F,N> as core::future::future::Future>::poll::ha7a9ee293c2ef6a0
[backend]   44:     0x55c2897aa9f2 - <tower::util::oneshot::Oneshot<S,Req> as core::future::future::Future>::poll::h83aff3bbf3292711
[backend]   45:     0x55c2897a981c - <axum::routing::route::RouteFuture<E> as core::future::future::Future>::poll::hd312b57ec3989c0a
[backend]   46:     0x55c289718e51 - <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll::h94ac416e75c1a8af
[backend]   47:     0x55c289719066 - <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll::h975e3323d611349a
  48:     0x55c28971ddc1 - <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll::hdf382bbf80cb41b0
[backend]   49:     0x55c28921c399 - <tower::util::map_response::MapResponseFuture<F,N> as core::future::future::Future>::poll::h2ec7b2fd077bd7cc
[backend]   50:     0x55c2897aa9f2 - <tower::util::oneshot::Oneshot<S,Req> as core::future::future::Future>::poll::h83aff3bbf3292711
[backend]   51:     0x55c2897a981c - <axum::routing::route::RouteFuture<E> as core::future::future::Future>::poll::hd312b57ec3989c0a
  52:     0x55c289718e51 - <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll::h94ac416e75c1a8af
[backend]   53:     0x55c289719066 - <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll::h975e3323d611349a
[backend]   54:     0x55c28971ddc1 - <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll::hdf382bbf80cb41b0
[backend]   55:     0x55c28921c399 - <tower::util::map_response::MapResponseFuture<F,N> as core::future::future::Future>::poll::h2ec7b2fd077bd7cc
[backend]   56:     0x55c2897aa9f2 - <tower::util::oneshot::Oneshot<S,Req> as core::future::future::Future>::poll::h83aff3bbf3292711
[backend]   57:     0x55c2897a981c - <axum::routing::route::RouteFuture<E> as core::future::future::Future>::poll::hd312b57ec3989c0a
[backend]   58:     0x55c289718e51 - <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll::h94ac416e75c1a8af
[backend]   59:     0x55c289719066 - <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll::h975e3323d611349a
[backend]   60:     0x55c28971ddc1 - <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll::hdf382bbf80cb41b0
  61:     0x55c28921c399 - <tower::util::map_response::MapResponseFuture<F,N> as core::future::future::Future>::poll::h2ec7b2fd077bd7cc
[backend]   62:     0x55c2897aa9f2 - <tower::util::oneshot::Oneshot<S,Req> as core::future::future::Future>::poll::h83aff3bbf3292711
[backend]   63:     0x55c2897a981c - <axum::routing::route::RouteFuture<E> as core::future::future::Future>::poll::hd312b57ec3989c0a
[backend]   64:     0x55c28971c212 - <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll::hba19eccfd33b557d
[backend]   65:     0x55c289718816 - <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll::h5acbca62fd02ea33
[backend]   66:     0x55c28971bd51 - <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll::hb6902a3bfb84edf7
[backend]   67:     0x55c28921c3c9 - <tower::util::map_response::MapResponseFuture<F,N> as core::future::future::Future>::poll::h85f544a0e230818e
[backend]   68:     0x55c2897aa9f2 - <tower::util::oneshot::Oneshot<S,Req> as core::future::future::Future>::poll::h83aff3bbf3292711
[backend]   69:     0x55c2897a981c - <axum::routing::route::RouteFuture<E> as core::future::future::Future>::poll::hd312b57ec3989c0a
[backend]   70:     0x55c28944842d - <tower_http::catch_panic::ResponseFuture<F,T> as core::future::future::Future>::poll::h52a88ef4391c2e9c
[backend]   71:     0x55c289716895 - <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll::h2a848368e866850a
[backend]   72:     0x55c28971659a - <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll::h0cd5bd8e67e306a2
[backend]   73:     0x55c28971dfe5 - <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll::hf382bf2a28dd611c
[backend]   74:     0x55c28921c3a9 - <tower::util::map_response::MapResponseFuture<F,N> as core::future::future::Future>::poll::h36cefbe07bc4d4cc
[backend]   75:     0x55c2897aa9f2 - <tower::util::oneshot::Oneshot<S,Req> as core::future::future::Future>::poll::h83aff3bbf3292711
[backend]   76:     0x55c2897a981c - <axum::routing::route::RouteFuture<E> as core::future::future::Future>::poll::hd312b57ec3989c0a
[backend]   77:     0x55c289718e51 - <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll::h94ac416e75c1a8af
[backend]   78:     0x55c289719066 - <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll::h975e3323d611349a
  79:     0x55c28971ddc1 - <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll::hdf382bbf80cb41b0
[backend]   80:     0x55c28921c399 - <tower::util::map_response::MapResponseFuture<F,N> as core::future::future::Future>::poll::h2ec7b2fd077bd7cc
[backend]   81:     0x55c2897aa9f2 - <tower::util::oneshot::Oneshot<S,Req> as core::future::future::Future>::poll::h83aff3bbf3292711
[backend]   82:     0x55c28928f72b - <tower_http::cors::ResponseFuture<F> as core::future::future::Future>::poll::h2bad863c9196a3da
[backend]   83:     0x55c289716f01 - <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll::h4b9eb2e0f64a27ca
[backend]   84:     0x55c28971bf96 - <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll::hb786a5965faf6591
[backend]   85:     0x55c289718c11 - <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll::h902f5f7c2cc76ceb
[backend]   86:     0x55c28921c3b9 - <tower::util::map_response::MapResponseFuture<F,N> as core::future::future::Future>::poll::h70df02974cc9b516
[backend]   87:     0x55c2897aa9f2 - <tower::util::oneshot::Oneshot<S,Req> as core::future::future::Future>::poll::h83aff3bbf3292711
  88:     0x55c2897a981c - <axum::routing::route::RouteFuture<E> as core::future::future::Future>::poll::hd312b57ec3989c0a
[backend]   89:     0x55c2897aac78 - <tower::util::oneshot::Oneshot<S,Req> as core::future::future::Future>::poll::hc8cf6bf848d5b9a8
[backend]   90:     0x55c2898f50bb - <axum::serve::Serve<M,S> as core::future::into_future::IntoFuture>::into_future::{{closure}}::{{closure}}::h3a55536b327ac876
[backend]   91:     0x55c2898d9d7e - tokio::runtime::task::core::Core<T,S>::poll::h403a39cc419c29d4
[backend]   92:     0x55c2898e04e5 - tokio::runtime::task::harness::Harness<T,S>::poll::hd133cd88808ad4d9
[backend]   93:     0x55c28aea260e - tokio::runtime::scheduler::multi_thread::worker::Context::run_task::h76e0d66dab160509
[backend]   94:     0x55c28aea1b3a - tokio::runtime::scheduler::multi_thread::worker::Context::run::h2d7f9eeef66392a3
[backend]   95:     0x55c28ae9c2a9 - tokio::runtime::context::runtime::enter_runtime::h015fce0062071bd8
[backend]   96:     0x55c28aea0e48 - tokio::runtime::scheduler::multi_thread::worker::run::h4dcb2888a44f7f05
[backend]   97:     0x55c28ae8a173 - <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll::h28901978ab2995af
[backend]   98:     0x55c28ae88407 - tokio::runtime::task::core::Core<T,S>::poll::h2894df602b0f8883
[backend]   99:     0x55c28ae840ba - tokio::runtime::task::harness::Harness<T,S>::poll::h39a10f3e27a5210a
[backend]  100:     0x55c28aea6700 - tokio::runtime::blocking::pool::Inner::run::hb7208c093d470d53
[backend]  101:     0x55c28ae92247 - std::sys_common::backtrace::__rust_begin_short_backtrace::ha3683379ee632dcd
[backend]  102:     0x55c28ae9adc9 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h0494fd2b2d48b9da
[backend]  103:     0x55c28aee0675 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h6b630278c760b971
[backend]                                at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/alloc/src/boxed.rs:2015:9
[backend]  104:     0x55c28aee0675 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h70462b441b6c0e1f
[backend]                                at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/alloc/src/boxed.rs:2015:9
 105:     0x55c28aee0675 - std::sys::pal::unix::thread::Thread::new::thread_start::h3631815ad38387d6
[backend]                                at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/sys/pal/unix/thread.rs:108:17
[backend]  106:     0x7fd482df1044 - <unknown>
[backend]  107:     0x7fd482e7161c - <unknown>
[backend]  108:                0x0 - <unknown>
[frontend] ClientError: GraphQL Error (Code: 500): {"response":{"error":"Service panicked","status":500,"headers":{}},"request":{"query":"query MetadataList($input: MetadataListInput!) {\n  metadataList(input: $input) {\n    details {\n      total\n      nextPage\n    }\n    items {\n      averageRating\n      data {\n        ...MetadataSearchItemPart\n      }\n    }\n  }\n}\n\nfragment MetadataSearchItemPart on MetadataSearchItem {\n  identifier\n  title\n  image\n  publishYear\n}","variables":{"input":{"lot":"ANIME","search":{"page":1},"sort":{"order":"DESC","by":"LAST_SEEN"},"filter":{"general":"COMPLETED"}}}}}
[frontend]     at makeRequest (file:///home/ryot/node_modules/graphql-request/src/index.ts:426:11)
[frontend]     at processTicksAndRejections (node:internal/process/task_queues:95:5)
[frontend]     at file:///home/ryot/build/server/index.js?t=1713920527000:11209:30
[frontend]     at loader$c (file:///home/ryot/build/server/index.js?t=1713920527000:11202:36)
[frontend]     at Object.callRouteLoaderRR (/home/ryot/node_modules/@remix-run/server-runtime/dist/data.js:52:16)
[frontend]     at callLoaderOrAction (/home/ryot/node_modules/@remix-run/router/router.ts:4043:16)
[frontend]     at async Promise.all (index 2)
[frontend]     at loadRouteData (/home/ryot/node_modules/@remix-run/router/router.ts:3320:19)
[frontend]     at queryImpl (/home/ryot/node_modules/@remix-run/router/router.ts:3101:20)
[frontend]     at Object.query (/home/ryot/node_modules/@remix-run/router/router.ts:2977:18) {
[frontend]   response: {
[frontend]     error: 'Service panicked',
[frontend]     status: 500,
[frontend]     headers: Headers { [Symbol(map)]: [Object: null prototype] }
[frontend]   },
[frontend]   request: {
[frontend]     query: 'query MetadataList($input: MetadataListInput!) {\n' +
[frontend]       '  metadataList(input: $input) {\n' +
[frontend]       '    details {\n' +
[frontend]       '      total\n' +
[frontend]       '      nextPage\n' +
[frontend]       '    }\n' +
[frontend]       '    items {\n' +
[frontend]       '      averageRating\n' +
[frontend]       '      data {\n' +
[frontend]       '        ...MetadataSearchItemPart\n' +
[frontend]       '      }\n' +
[frontend]       '    }\n' +
[frontend]       '  }\n' +
[frontend]       '}\n' +
[frontend]       '\n' +
[frontend]       'fragment MetadataSearchItemPart on MetadataSearchItem {\n' +
[frontend]       '  identifier\n' +
[frontend]       '  title\n' +
[frontend]       '  image\n' +
[frontend]       '  publishYear\n' +
[frontend]       '}',
[frontend]     variables: { input: [Object] }
[frontend]   }
[frontend] }
[frontend] GET /media/list/anime?generalFilter=COMPLETED 500 - - 73.541 ms
```

**Comment by IgnisDa** [comment]
Weird. I can not reproduce this. Can you create an export of your db and email it to me? THe instructions to create a database dump are in the exporting docs.

**Comment by IgnisDa** [comment]
@hollowdew I have found the fixed the issue. Will be fixed in when I publish the next release.
