### ISSUE TITLE
[BUG] Searching using spacess cause errors

### ISSUE THREAD

**Issue by acelinkio** [IgnisDa/ryot#854]
Ryot version 5.5.3

Searching for titles with a space in the name appears to be causing crashes.  Have tried with books/shows/movies and see a similar error as the following.

```log
[frontend] GET /media/search/movie?query=wolf+of+wall&_data=root 200 - - 9.852 ms
[frontend] ClientError: Query Error: error occurred while decoding column 1: mismatched types; Rust type `core::option::Option<i32>` (as SQL type `INT4`) is not compatible with SQL type `TEXT`: {"response":{"data":null,"errors":[{"message":"Query Error: error occurred while decoding column 1: mismatched types; Rust type `core::option::Option<i32>` (as SQL type `INT4`) is not compatible with SQL type `TEXT`","locations":[{"line":2,"column":3}],"path":["metadataSearch"]}],"status":200,"headers":{}},"request":{"query":"query MetadataSearch($input: MetadataSearchInput!) {\n  metadataSearch(input: $input) {\n    details {\n      total\n      nextPage\n    }\n    items {\n      databaseId\n      hasInteracted\n      item {\n        identifier\n        title\n        image\n        publishYear\n      }\n    }\n  }\n}","variables":{"input":{"lot":"MOVIE","search":{"page":1,"query":"wolf of wall"},"source":"TMDB"}}}}
[frontend]     at makeRequest (file:///home/ryot/node_modules/graphql-request/src/index.ts:426:11)
[frontend]     at processTicksAndRejections (node:internal/process/task_queues:95:5)
[frontend]     at file:///home/ryot/build/server/index.js?t=1717242166000:10693:32
[frontend]     at loader$c (file:///home/ryot/build/server/index.js?t=1717242166000:10665:36)
[frontend]     at Object.callRouteLoaderRR (/home/ryot/node_modules/@remix-run/server-runtime/dist/data.js:52:16)
[frontend]     at callLoaderOrAction (/home/ryot/node_modules/@remix-run/router/router.ts:4043:16)
[frontend]     at async Promise.all (index 0)
[frontend]     at loadRouteData (/home/ryot/node_modules/@remix-run/router/router.ts:3320:19)
[frontend]     at queryImpl (/home/ryot/node_modules/@remix-run/router/router.ts:3101:20)
[frontend]     at Object.queryRoute (/home/ryot/node_modules/@remix-run/router/router.ts:3041:18) {
[frontend]   response: {
[frontend]     data: null,
[frontend]     errors: [ [Object] ],
[frontend]     status: 200,
[frontend]     headers: Headers { [Symbol(map)]: [Object: null prototype] }
[frontend]   },
[frontend]   request: {
[frontend]     query: 'query MetadataSearch($input: MetadataSearchInput!) {\n' +
[frontend]       '  metadataSearch(input: $input) {\n' +
[frontend]       '    details {\n' +
[frontend]       '      total\n' +
[frontend]       '      nextPage\n' +
[frontend]       '    }\n' +
[frontend]       '    items {\n' +
[frontend]       '      databaseId\n' +
[frontend]       '      hasInteracted\n' +
[frontend]       '      item {\n' +
[frontend]       '        identifier\n' +
[frontend]       '        title\n' +
[frontend]       '        image\n' +
[frontend]       '        publishYear\n' +
[frontend]       '      }\n' +
[frontend]       '    }\n' +
[frontend]       '  }\n' +
[frontend]       '}',
[frontend]     variables: { input: [Object] }
[frontend]   }
[frontend] }
```

Let me know if you are unable to reproduce.

**Comment by IgnisDa** [comment]
Please upgrade to the latest version, and LMK if the error still occurs.

**Comment by IgnisDa** [comment]
Please upgrade to `v5.5.4`.
