### ISSUE TITLE
[BUG] - After upgrade to 5.5.6 cannot access to Ryot

### ISSUE THREAD

**Issue by SirMartin** [IgnisDa/ryot#859]
Hi @IgnisDa 

I just updated my instance to 5.5.6, I was on 5.4.4, and after the update it appears a black screen, saying to me that I need to log out and try to log in, and if not work, so yes here I am, 😄 

![image](https://github.com/IgnisDa/ryot/assets/854646/db61a7d5-b93e-4609-b825-0def18362ea6)

I clicked multiple times to log out and cleared the cache, storage and everything, but it still doesn't work.

I got a 500 error in the auth.
![image](https://github.com/IgnisDa/ryot/assets/854646/f8975ee7-2dc8-4189-8e08-2c72101f6306)

I got this errors on the logs:

```[frontend] [remix-serve] http://localhost:3000 (http://192.168.128.4:3000)
[frontend] GET / 302 - - 37.843 ms
[proxy] {"level":"error","ts":1717928765.0859132,"logger":"http.log.error","msg":"dial tcp 127.0.0.1:5000: connect: connection refused","request":{"remote_ip":"127.0.0.1","remote_port":"42704","client_ip":"127.0.0.1","proto":"HTTP/1.1","method":"POST","host":"localhost:8000","uri":"/backend/graphql","headers":{"Connection":["keep-alive"],"Content-Type":["application/json"],"Accept":["*/*"],"Content-Length":["146"],"User-Agent":["node-fetch/1.0 (+https://github.com/bitinn/node-fetch)"],"Accept-Encoding":["gzip,deflate"]}},"duration":0.000599366,"status":502,"err_id":"zgw036rg4","err_trace":"reverseproxy.statusError (reverseproxy.go:1265)"}
[proxy] {"level":"error","ts":1717928765.0875921,"logger":"http.log.error","msg":"dial tcp 127.0.0.1:5000: connect: connection refused","request":{"remote_ip":"127.0.0.1","remote_port":"42718","client_ip":"127.0.0.1","proto":"HTTP/1.1","method":"POST","host":"localhost:8000","uri":"/backend/graphql","headers":{"Connection":["keep-alive"],"Content-Type":["application/json"],"Accept":["*/*"],"Content-Length":["239"],"User-Agent":["node-fetch/1.0 (+https://github.com/bitinn/node-fetch)"],"Accept-Encoding":["gzip,deflate"]}},"duration":0.000442076,"status":502,"err_id":"4m8f0c7vc","err_trace":"reverseproxy.statusError (reverseproxy.go:1265)"}
[frontend] ClientError: GraphQL Error (Code: 502): {"response":{"error":"","status":502,"headers":{}},"request":{"query":"query CoreEnabledFeatures {\n  coreEnabledFeatures {\n    fileStorage\n    signupAllowed\n  }\n}"}}
[frontend]     at makeRequest (file:///home/ryot/node_modules/graphql-request/src/index.ts:426:11)
[frontend]     at processTicksAndRejections (node:internal/process/task_queues:95:5)
[frontend]     at getCoreEnabledFeatures (file:///home/ryot/build/server/index.js?t=1717457584000:782:35)
[frontend]     at async Promise.all (index 0)
[frontend]     at loader (file:///home/ryot/build/server/index.js?t=1717457584000:13239:46)
[frontend]     at Object.callRouteLoaderRR (/home/ryot/node_modules/@remix-run/server-runtime/dist/data.js:52:16)
[frontend]     at callLoaderOrAction (/home/ryot/node_modules/@remix-run/router/router.ts:4043:16)
[frontend]     at async Promise.all (index 1)
[frontend]     at loadRouteData (/home/ryot/node_modules/@remix-run/router/router.ts:3320:19)
[frontend]     at queryImpl (/home/ryot/node_modules/@remix-run/router/router.ts:3101:20) {
[frontend]   response: {
[frontend]     error: '',
[frontend]     status: 502,
[frontend]     headers: Headers { [Symbol(map)]: [Object: null prototype] }
[frontend]   },
[frontend]   request: {
[frontend]     query: 'query CoreEnabledFeatures {\n' +
[frontend]       '  coreEnabledFeatures {\n' +
[frontend]       '    fileStorage\n' +
[frontend]       '    signupAllowed\n' +
[frontend]       '  }\n' +
[frontend]       '}',
[frontend]     variables: undefined
[frontend]   }

[frontend] }
```

And every time I restarted the container, it appears to launch this migration.

```
[backend] 2024-06-09T10:26:50.766676Z  INFO sea_orm_migration::migrator: Applying all pending migrations
[backend] 2024-06-09T10:26:50.779704Z  INFO sea_orm_migration::migrator: Applying migration 'm20240531_create_queued_notification'
```

Thanks in advance.

**Comment by IgnisDa** [comment]
That's weird. Can you email me a database dump?

**Comment by SirMartin** [comment]
Ok, not sure what happened, but I made nothing, and now it works, I just watch a TV show, and I opened ryot and while loading I remembered that this morning didn't work, but ..., it works, I registered, and logged in, also tried on the computer and the mobile, and works perfectly. So I just close this weird issue.

**Comment by IgnisDa** [comment]
Yeah the final migration is extremely heavy so ig it took a lot of time for you. Glad to know it's working now.
