### ISSUE TITLE
[BUG] Since latest update, the option to repeat a workout is no more working

### ISSUE THREAD

**Issue by edersong** [IgnisDa/ryot#896]
Since latest update, the option to repeat a workout is no more working.
When we click selecting the option to repeat a workout it simple is not responding.

**Comment by IgnisDa** [comment]
It seems to be working albeit a little slow. Please clear your cookies and try again. I will add a loader spinner to it too in the next update.

**Comment by edersong** [comment]
Updated and tried to copy a workout again, but it still not working even clearing browser cookies.
Tried to copy a workout, waited for longer 30 minutes and nothing happened.

Here is what is being reported by frontend container:
```
[frontend] Error: No route matches URL "/backend/graphql"
[frontend]     at getInternalRouterError (/home/ryot/node_modules/@remix-run/router/router.ts:5353:5)
[frontend]     at Object.query (/home/ryot/node_modules/@remix-run/router/router.ts:3462:19)
[frontend]     at handleDocumentRequest (/home/ryot/node_modules/@remix-run/server-runtime/dist/server.js:268:35)
[frontend]     at requestHandler (/home/ryot/node_modules/@remix-run/server-runtime/dist/server.js:160:24)
[frontend]     at /home/ryot/node_modules/@remix-run/express/dist/server.js:41:28
[frontend]     at processTicksAndRejections (node:internal/process/task_queues:95:5)
[frontend] Error: No route matches URL "/backend/graphql"
[frontend]     at getInternalRouterError (/home/ryot/node_modules/@remix-run/router/router.ts:5353:5)
[frontend]     at Object.query (/home/ryot/node_modules/@remix-run/router/router.ts:3462:19)
[frontend]     at handleDocumentRequest (/home/ryot/node_modules/@remix-run/server-runtime/dist/server.js:268:35)
[frontend]     at requestHandler (/home/ryot/node_modules/@remix-run/server-runtime/dist/server.js:160:24)
[frontend]     at /home/ryot/node_modules/@remix-run/express/dist/server.js:41:28
[frontend]     at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by IgnisDa** [comment]
That doesn't sound right. Can you try opening the network tab in dev tools and try to repeat a workout?

Are you running the docker image or something custom setup? The front-end should not be handling requests to the backend.

**Comment by edersong** [comment]
I'm running the docker image. No custom setup.
Following your instructions, I got the following:

```
generals-CQmk6nd9.js:96 Uncaught (in promise) Error: GraphQL Error (Code: 404): {"response":{"status":404,"headers":{}},"request":{"query":"query UserExerciseDetails($input: UserExerciseDetailsInput!) {\n  userExerciseDetails(input: $input) {\n    collections {\n      ...CollectionPart\n    }\n    history {\n      workoutId\n      workoutName\n      workoutTime\n      index\n      sets {\n        lot\n        statistic {\n          ...WorkoutSetStatisticPart\n        }\n      }\n    }\n    details {\n      exerciseId\n      createdOn\n      lastUpdatedOn\n      exerciseNumTimesInteracted\n      exerciseExtraInformation {\n        lifetimeStats {\n          weight\n          reps\n          distance\n          duration\n          personalBestsAchieved\n        }\n        personalBests {\n          lot\n          sets {\n            workoutId\n            workoutDoneOn\n            exerciseIdx\n            setIdx\n            data {\n              statistic {\n                ...WorkoutSetStatisticPart\n              }\n              lot\n            }\n          }\n        }\n      }\n    }\n  }\n}\n\nfragment CollectionPart on Collection {\n  id\n  name\n  userId\n}\n\nfragment WorkoutSetStatisticPart on WorkoutSetStatistic {\n  duration\n  distance\n  reps\n  weight\n  oneRm\n  pace\n  volume\n}","variables":{"input":{"exerciseId":"94 - Remo/Deltoides posterior"}}}}
    at Ft (generals-CQmk6nd9.js:96:1617)
    at async Vi.request (generals-CQmk6nd9.js:96:4909)
```

and:

```
Request URL: https://ryot.whatevercom/backend/graphql
Request Method: POST
Status Code: 404 Not Found
Remote Address: 108.22.87.192:443
Referrer Policy: strict-origin-when-cross-origin
Alt-Svc: h3=":443"; ma=86400
Cf-Cache-Status: DYNAMIC
Cf-Ray: 89d60c084ac61b91-DUB
Content-Encoding: br
Content-Type: text/html; charset=utf-8
Date: Wed, 03 Jul 2024 10:03:40 GMT
Nel: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
Report-To: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v4?s=EfIdtLWgvnj3o600ZSTmirJe2dyz8eIDD4wNx%2FtK8dDHKZ%2BKxUYc%2FQMVhLPHwTfmgjNGoUFqqHbblUGCePMBtoMIFKclc7UAJ6RIzYoVFLwuuEX7LzlNYG2yjHQF22UEAUnxA%3D%3D"}],"group":"cf-nel","max_age":604800}
Server: cloudflare
Vary: Accept-Encoding
:authority: ryot.whatever.com
:method: POST
:path: /backend/graphql
:scheme: https
Accept: application/graphql-response+json, application/json
Accept-Encoding: gzip, deflate, br, zstd
Accept-Language: es-ES,es;q=0.9,pt-BR;q=0.8,pt;q=0.7,en-US;q=0.6,en;q=0.5
Authorization: Bearer eyJ0eXAiOiJK1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c3JfdjhOaElrTzZVTUNrIiwiZXhwIjoxNzI3Nzc0MzQ5LCJpYXQiOjE3MTk5OTgzNDl9.GLdp47ffvKWLMDdNCSy1vAwBl0AF2WOjlshhxtsxHbw
Content-Length: 371
Content-Type: application/json
Cookie: CF_AppSession=need7ffd3bd06644; CF_Authorization=eyJhbGciOiJSUzI1NiIsImtpZCI6IjBlYzQwMmE1MTE0MGRjNzkyNTk0NWUwOTMxY2ZhNWM2MzY4NzMzNDBhZGMxZjczMzA1YWE3ZGU1Y2E3ZGE4YTAifQ.eyJhdWQiOlsiMTAzYzM0OTJlMzI1NTZjNzE3NTg3NGM2MDk3ZjVkMGRhZWZlOWU4YmQ5Zjk4YTViODY0NDM3Y2Q0ZTc3MDM1YSJdLCJlbWFpbCI6ImVkZXJzb25nQGdtYWlsLmNvbSIsImV4cCI6MTcyMjYyNjM0MywiaWF0IjoxNzE5OTk4MzQzLCJuYmYiOjE3MTk5OTgzNDMsImlzcyI6Imh0dHBzOi8vZWRlcnNvbmcuY2xvdWRmbGFyZWFjY2Vzcy5jb20iLCJ0eXBlIjoiYXBwIiwiaWRlbnRpdHlfbm9uY2UiOiJLT1I1QmNVaGppM0xOU0FEIiwic3ViIjoiZGVlMWNjYjgtMjljZC01NTMyLWI4YzgtMzM4OWY5ZjI2YTg2IiwiY291bnRyeSI6IkVTIn0.jqr_pOj-y1fieNihjiA0vSceMefd4LhR68x6vMhlkAYO0bnGVY0SQQ5yPSFd94TdamSaDmjNPy0VVSmYCGlibnYFG5uEaWXmgPTwjk_qau4xtt4Q0LJa9gl0OHOkNomjtz_HIvbSLDLCtg6ZgV-coSNAxPaKWLmeCf21jXQAntEEZo9FWZ29jUj_6ryOEcbrsPgJU6gfcadzH0Tzn6r7_cSeL7oEwkdZT5iObSgTiyPmAzfoZDsdUvAPppItrvC21IQ50t9YETspCGZhWffbOCSfOvjKbhKnObQuGXyRc1lK1sI1IC5d9X1z7hJLL2iPqcUqa3Bdhv_4vQtTNxrEQg; CoreDetails=%7B%22isPro%22%3Afalse%2C%22timezone%22%3A%22Europe%2FMadrid%22%2C%22docsLink%22%3A%22https%3A%2F%2Fdocs.ryot.io%22%2C%22pageLimit%22%3A20%2C%22websiteUrl%22%3A%22https%3A%2F%2Fryot.io%2Ffeatures%22%2C%22authorName%22%3A%22ignisda%22%2C%22oidcEnabled%22%3Afalse%2C%22repositoryLink%22%3A%22https%3A%2F%2Fgithub.com%2Fignisda%2Fryot%22%2C%22localAuthDisabled%22%3Afalse%2C%22tokenValidForDays%22%3A90%7D; UserPreferences=%7B%22general%22%3A%7B%22reviewScale%22%3A%22OUT_OF_HUNDRED%22%2C%22displayNsfw%22%3Afalse%2C%22dashboard%22%3A%5B%7B%22section%22%3A%22SUMMARY%22%2C%22hidden%22%3Afalse%2C%22numElements%22%3Anull%7D%2C%7B%22section%22%3A%22IN_PROGRESS%22%2C%22hidden%22%3Afalse%2C%22numElements%22%3A4%7D%2C%7B%22section%22%3A%22UPCOMING%22%2C%22hidden%22%3Afalse%2C%22numElements%22%3A15%7D%5D%2C%22disableYankIntegrations%22%3Afalse%2C%22disableNavigationAnimation%22%3Afalse%2C%22disableVideos%22%3Afalse%2C%22watchProviders%22%3A%5B%22Netflix%22%2C%22Amazon%20Prime%22%2C%22Disney%2B%22%2C%22Globo%20Play%22%2C%22Cinema%22%5D%2C%22disableReviews%22%3Afalse%2C%22disableWatchProviders%22%3Afalse%7D%2C%22fitness%22%3A%7B%22measurements%22%3A%7B%22custom%22%3A%5B%7B%22name%22%3A%22sugar_level%22%2C%22dataType%22%3A%22DECIMAL%22%7D%5D%2C%22inbuilt%22%3A%7B%22weight%22%3Atrue%2C%22bodyMassIndex%22%3Atrue%2C%22totalBodyWater%22%3Atrue%2C%22muscle%22%3Atrue%2C%22leanBodyMass%22%3Afalse%2C%22bodyFat%22%3Atrue%2C%22boneMass%22%3Atrue%2C%22visceralFat%22%3Atrue%2C%22waistCircumference%22%3Atrue%2C%22waistToHeightRatio%22%3Afalse%2C%22hipCircumference%22%3Afalse%2C%22waistToHipRatio%22%3Afalse%2C%22chestCircumference%22%3Afalse%2C%22thighCircumference%22%3Afalse%2C%22bicepsCircumference%22%3Afalse%2C%22neckCircumference%22%3Afalse%2C%22bodyFatCaliper%22%3Afalse%2C%22chestSkinfold%22%3Afalse%2C%22abdominalSkinfold%22%3Afalse%2C%22thighSkinfold%22%3Afalse%2C%22basalMetabolicRate%22%3Afalse%2C%22totalDailyEnergyExpenditure%22%3Afalse%2C%22calories%22%3Afalse%7D%7D%2C%22exercises%22%3A%7B%22saveHistory%22%3A99999%2C%22unitSystem%22%3A%22METRIC%22%7D%7D%2C%22notifications%22%3A%7B%22toSend%22%3A%5B%22METADATA_PUBLISHED%22%2C%22METADATA_STATUS_CHANGED%22%2C%22METADATA_RELEASE_DATE_CHANGED%22%2C%22METADATA_NUMBER_OF_SEASONS_CHANGED%22%2C%22METADATA_EPISODE_RELEASED%22%2C%22METADATA_EPISODE_NAME_CHANGED%22%2C%22METADATA_CHAPTERS_OR_EPISODES_CHANGED%22%2C%22METADATA_EPISODE_IMAGES_CHANGED%22%2C%22PERSON_MEDIA_ASSOCIATED%22%5D%2C%22enabled%22%3Atrue%7D%2C%22featuresEnabled%22%3A%7B%22others%22%3A%7B%22calendar%22%3Atrue%2C%22collections%22%3Atrue%7D%2C%22fitness%22%3A%7B%22enabled%22%3Atrue%2C%22workouts%22%3Atrue%2C%22measurements%22%3Atrue%7D%2C%22media%22%3A%7B%22enabled%22%3Atrue%2C%22anime%22%3Afalse%2C%22audioBook%22%3Afalse%2C%22book%22%3Afalse%2C%22manga%22%3Afalse%2C%22movie%22%3Atrue%2C%22podcast%22%3Afalse%2C%22show%22%3Atrue%2C%22videoGame%22%3Afalse%2C%22visualNovel%22%3Afalse%2C%22people%22%3Atrue%2C%22groups%22%3Afalse%2C%22genres%22%3Afalse%7D%7D%7D; UserDetails=%7B%22__typename%22%3A%22User%22%2C%22id%22%3A%22usr_v8NhIkO6UMCk%22%2C%22lot%22%3A%22ADMIN%22%2C%22name%22%3A%22ederson%22%2C%22oidcIssuerId%22%3Anull%2C%22isDemo%22%3Anull%7D; Auth=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c3JfdjhOaElrTzZVTUNrIiwiZXhwIjoxNzI3Nzc0MzQ5LCJpYXQiOjE3MTk5OTgzNDl9.GLdp47ffvKWLMDdNCSy1vAwBl0AF2WOjlshhxtsxHbw
Origin: https://ryot.whatevercom.com
Priority: u=1, i
Referer: https://ryot.whatevercom.com/fitness/workouts/wor_HYRJcZKE8vbS
Sec-Ch-Ua: "Not/A)Brand";v="8", "Chromium";v="126", "Google Chrome";v="126"
Sec-Ch-Ua-Mobile: ?0
Sec-Ch-Ua-Platform: "Windows"
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-origin
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36
```

**Comment by IgnisDa** [comment]
That is very weird. Is the server booting up correctly? What version are you on?

**Comment by edersong** [comment]
yes, server is running fine and all of other funciones seems that are working fine.
I'm on the v6.4.6, I guess because upadated yesterday but there is no information on the GUI (It's a suggestion that I have: to inform which version we are on the footer)

**Comment by IgnisDa** [comment]
Can you show the entire docker logs? Maybe the proxy is misbehaving?

**Comment by IgnisDa** [comment]
Also did you upgrade the server after a long time? The resource routes were removed long back (requests go directly from frontend to backend with a BFF hop).

**Comment by edersong** [comment]
I use to update almost daily.
I'm running https behind nginx and Cloudflare
Here is the docker logs that I have:

```
[frontend]     at getInternalRouterError (/home/ryot/node_modules/@remix-run/router/router.ts:5353:5)
[frontend]     at Object.query (/home/ryot/node_modules/@remix-run/router/router.ts:3462:19)
[frontend]     at handleDocumentRequest (/home/ryot/node_modules/@remix-run/server-runtime/dist/server.js:268:35)
[frontend]     at requestHandler (/home/ryot/node_modules/@remix-run/server-runtime/dist/server.js:160:24)
[frontend]     at /home/ryot/node_modules/@remix-run/express/dist/server.js:41:28
[frontend]     at processTicksAndRejections (node:internal/process/task_queues:95:5)
[frontend] Error: No route matches URL "/backend/graphql"
[frontend]     at getInternalRouterError (/home/ryot/node_modules/@remix-run/router/router.ts:5353:5)
[frontend]     at Object.query (/home/ryot/node_modules/@remix-run/router/router.ts:3462:19)
[frontend]     at handleDocumentRequest (/home/ryot/node_modules/@remix-run/server-runtime/dist/server.js:268:35)
[frontend]     at requestHandler (/home/ryot/node_modules/@remix-run/server-runtime/dist/server.js:160:24)
[frontend]     at /home/ryot/node_modules/@remix-run/express/dist/server.js:41:28
[frontend]     at processTicksAndRejections (node:internal/process/task_queues:95:5)
[frontend] Error: No route matches URL "/backend/graphql"
[frontend]     at getInternalRouterError (/home/ryot/node_modules/@remix-run/router/router.ts:5353:5)
[frontend]     at Object.query (/home/ryot/node_modules/@remix-run/router/router.ts:3462:19)
[frontend]     at handleDocumentRequest (/home/ryot/node_modules/@remix-run/server-runtime/dist/server.js:268:35)
[frontend]     at requestHandler (/home/ryot/node_modules/@remix-run/server-runtime/dist/server.js:160:24)
[frontend]     at /home/ryot/node_modules/@remix-run/express/dist/server.js:41:28
[frontend]     at processTicksAndRejections (node:internal/process/task_queues:95:5)
[frontend] Error: No route matches URL "/backend/graphql"
[frontend]     at getInternalRouterError (/home/ryot/node_modules/@remix-run/router/router.ts:5353:5)
[frontend]     at Object.query (/home/ryot/node_modules/@remix-run/router/router.ts:3462:19)
[frontend]     at handleDocumentRequest (/home/ryot/node_modules/@remix-run/server-runtime/dist/server.js:268:35)
[frontend]     at requestHandler (/home/ryot/node_modules/@remix-run/server-runtime/dist/server.js:160:24)
[frontend]     at /home/ryot/node_modules/@remix-run/express/dist/server.js:41:28
[frontend]     at processTicksAndRejections (node:internal/process/task_queues:95:5)
[frontend] Error: No route matches URL "/backend/graphql"
[frontend]     at getInternalRouterError (/home/ryot/node_modules/@remix-run/router/router.ts:5353:5)
[frontend]     at Object.query (/home/ryot/node_modules/@remix-run/router/router.ts:3462:19)
[frontend]     at handleDocumentRequest (/home/ryot/node_modules/@remix-run/server-runtime/dist/server.js:268:35)
[frontend]     at requestHandler (/home/ryot/node_modules/@remix-run/server-runtime/dist/server.js:160:24)
[frontend]     at /home/ryot/node_modules/@remix-run/express/dist/server.js:41:28
[frontend]     at processTicksAndRejections (node:internal/process/task_queues:95:5)
[frontend] Error: No route matches URL "/backend/graphql"
[frontend]     at getInternalRouterError (/home/ryot/node_modules/@remix-run/router/router.ts:5353:5)
[frontend]     at Object.query (/home/ryot/node_modules/@remix-run/router/router.ts:3462:19)
[frontend]     at handleDocumentRequest (/home/ryot/node_modules/@remix-run/server-runtime/dist/server.js:268:35)
[frontend]     at requestHandler (/home/ryot/node_modules/@remix-run/server-runtime/dist/server.js:160:24)
[frontend]     at /home/ryot/node_modules/@remix-run/express/dist/server.js:41:28
[frontend]     at processTicksAndRejections (node:internal/process/task_queues:95:5)
[frontend] Error: No route matches URL "/backend/graphql"
[frontend]     at getInternalRouterError (/home/ryot/node_modules/@remix-run/router/router.ts:5353:5)
[frontend]     at Object.query (/home/ryot/node_modules/@remix-run/router/router.ts:3462:19)
[frontend]     at handleDocumentRequest (/home/ryot/node_modules/@remix-run/server-runtime/dist/server.js:268:35)
[frontend]     at requestHandler (/home/ryot/node_modules/@remix-run/server-runtime/dist/server.js:160:24)
[frontend]     at /home/ryot/node_modules/@remix-run/express/dist/server.js:41:28
[frontend]     at processTicksAndRejections (node:internal/process/task_queues:95:5)
[frontend] Error: No route matches URL "/backend/graphql"
[frontend]     at getInternalRouterError (/home/ryot/node_modules/@remix-run/router/router.ts:5353:5)
[frontend]     at Object.query (/home/ryot/node_modules/@remix-run/router/router.ts:3462:19)
[frontend]     at handleDocumentRequest (/home/ryot/node_modules/@remix-run/server-runtime/dist/server.js:268:35)
[frontend]     at requestHandler (/home/ryot/node_modules/@remix-run/server-runtime/dist/server.js:160:24)
[frontend]     at /home/ryot/node_modules/@remix-run/express/dist/server.js:41:28
[frontend]     at processTicksAndRejections (node:internal/process/task_queues:95:5)
[frontend] Error: No route matches URL "/backend/graphql"
[frontend]     at getInternalRouterError (/home/ryot/node_modules/@remix-run/router/router.ts:5353:5)
[frontend]     at Object.query (/home/ryot/node_modules/@remix-run/router/router.ts:3462:19)
[frontend]     at handleDocumentRequest (/home/ryot/node_modules/@remix-run/server-runtime/dist/server.js:268:35)
[frontend]     at requestHandler (/home/ryot/node_modules/@remix-run/server-runtime/dist/server.js:160:24)
[frontend]     at /home/ryot/node_modules/@remix-run/express/dist/server.js:41:28
[frontend]     at processTicksAndRejections (node:internal/process/task_queues:95:5)
[frontend] Error: No route matches URL "/backend/graphql"
[frontend]     at getInternalRouterError (/home/ryot/node_modules/@remix-run/router/router.ts:5353:5)
[frontend]     at Object.query (/home/ryot/node_modules/@remix-run/router/router.ts:3462:19)
[frontend]     at handleDocumentRequest (/home/ryot/node_modules/@remix-run/server-runtime/dist/server.js:268:35)
[frontend]     at requestHandler (/home/ryot/node_modules/@remix-run/server-runtime/dist/server.js:160:24)
[frontend]     at /home/ryot/node_modules/@remix-run/express/dist/server.js:41:28
[frontend]     at processTicksAndRejections (node:internal/process/task_queues:95:5)
[frontend] POST /backend/graphql 404 - - 4.761 ms
[frontend] POST /backend/graphql 404 - - 3.404 ms
[frontend] Error: No route matches URL "/backend/graphql"
[frontend]     at getInternalRouterError (/home/ryot/node_modules/@remix-run/router/router.ts:5353:5)
[frontend]     at Object.query (/home/ryot/node_modules/@remix-run/router/router.ts:3462:19)
[frontend]     at handleDocumentRequest (/home/ryot/node_modules/@remix-run/server-runtime/dist/server.js:268:35)
[frontend]     at requestHandler (/home/ryot/node_modules/@remix-run/server-runtime/dist/server.js:160:24)
[frontend]     at /home/ryot/node_modules/@remix-run/express/dist/server.js:41:28
[frontend]     at processTicksAndRejections (node:internal/process/task_queues:95:5)
[frontend] POST /backend/graphql 404 - - 4.330 ms
[frontend] POST /backend/graphql 404 - - 5.222 ms
[frontend] POST /backend/graphql 404 - - 4.039 ms
[frontend] POST /backend/graphql 404 - - 4.948 ms
[frontend] POST /backend/graphql 404 - - 3.750 ms
[frontend] POST /backend/graphql 404 - - 4.653 ms
[frontend] POST /backend/graphql 404 - - 3.717 ms
[frontend] POST /backend/graphql 404 - - 3.223 ms
[frontend] POST /backend/graphql 404 - - 3.910 ms
[frontend] POST /backend/graphql 404 - - 3.336 ms
[frontend] GET / 200 - - 150.485 ms
[frontend] GET /_root.data 200 - - 73.122 ms
[frontend] GET /media/item/met_Aa2Pa-2XOXE3.data 200 - - 92.771 ms
[frontend] GET /media/list/movie.data 200 - - 115.011 ms
[frontend] GET /media/list/movie.data?query=superman 200 - - 73.336 ms
[frontend] GET /media/search/movie.data?query=superman 200 - - 508.855 ms
[frontend] POST /actions?intent=commitMedia 200 - - 1413.310 ms
[frontend] GET /media/item/met_RRcsUoQpjO8L.data 200 - - 43.616 ms
[frontend] POST /actions.data?intent=addEntityToCollection 202 - - 82.883 ms
[frontend] GET /media/item/met_RRcsUoQpjO8L.data 200 - - 45.919 ms
[frontend] GET /settings/preferences.data 200 - - 57.144 ms
[frontend] GET /_root.data 200 - - 63.168 ms
```

**Comment by edersong** [comment]
- DATABASE_URL=postgres://user:password@ryot_db:5432/postgres
      - TZ=Europe/anywhere
      - FRONTEND_URL=https://ryot.anywhere.com
      - SCHEDULER_USER_CLEANUP_EVERY=2
      - SERVER_PERSON_OUTDATED_THRESHOLD=365
      - SERVER_DEPLOY_ADMIN_JOBS_ALLOWED=true
      - USERS_ALLOW_REGISTRATION=false
      - FILE_STORAGE_S3_ACCESS_KEY_ID=key
      - FILE_STORAGE_S3_SECRET_ACCESS_KEY=secret_key
      - FILE_STORAGE_S3_BUCKET_NAME=ryot
      - FILE_STORAGE_S3_URL=https://bucket.anywhere.com

**Comment by IgnisDa** [comment]
Can you try `curl https://yot.anywhere.com/backend/graphql`?

Also `SCHEDULER_USER_CLEANUP_EVERY` `SERVER_PERSON_OUTDATED_THRESHOLD` `SERVER_DEPLOY_ADMIN_JOBS_ALLOWED` env variables have been removed so you can remove them too.

**Comment by IgnisDa** [comment]
Moreover can you clicking on the play buttons here (in dashboard)? They also use the client side graphql endpoint. 

![image](https://github.com/IgnisDa/ryot/assets/60938164/5ce3470f-9191-40cb-84ba-9c905de2df10)

**Comment by edersong** [comment]
`curl https://ryot.anywhere.com/backend/graphql` results:

```
<!DOCTYPE html><html lang="en"><head><meta charSet="utf-8"/><meta name="viewport" content="minimum-scale=1, initial-scale=1, width=device-width, shrink-to-fit=no, user-scalable=no, viewport-fit=cover"/><link rel="manifest" href="/manifest.json"/><title>Ryot</title><meta name="description" content="The only self hosted tracker you will ever need."/><meta property="og:image" content="https://raw.githubusercontent.com/IgnisDa/ryot/main/libs/assets/icon-512x512.png"/><link rel="stylesheet" href="/assets/root-BKilLPaM.css"/><link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png"/><link rel="icon" type="image/png" sizes="32x32" href="https://raw.githubusercontent.com/IgnisDa/ryot/main/libs/assets/favicon-32x32.png"/><link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;600;700;800;900&amp;display=swap"/></head><body><div>We encountered an error. If you recently upgraded the server, you may have to logout and login again. If the error still persists, please create a new issue on<!-- --> <a href="https://github.com/ignisda/ryot/issues" target="_blank" rel="noreferrer noopener">GitHub</a>.</div><form method="post" action="/actions?intent=logout"><button type="submit">Logout</button></form><link rel="modulepreload" href="/assets/manifest-49b49c4e.js"/><link rel="modulepreload" href="/assets/entry.client-De8lnbfs.js"/><link rel="modulepreload" href="/assets/components-B0SwW8mj.js"/><link rel="modulepreload" href="/assets/client-B35dQk-l.js"/><link rel="modulepreload" href="/assets/createReactComponent-C96uy1fo.js"/><link rel="modulepreload" href="/assets/use-id-NmdiCPNA.js"/><link rel="modulepreload" href="/assets/use-merged-ref-DMOT6dm1.js"/><link rel="modulepreload" href="/assets/OptionalPortal-CsKrXo0H.js"/><link rel="modulepreload" href="/assets/Group-D0M0rpgZ.js"/><link rel="modulepreload" href="/assets/CloseButton-Cyssfho-.js"/><link rel="modulepreload" href="/assets/Paper-C9hSsny-.js"/><link rel="modulepreload" href="/assets/Modal-CbXyGmRf.js"/><link rel="modulepreload" href="/assets/Text-BpZk_jdE.js"/><link rel="modulepreload" href="/assets/Button-CMxsAb7D.js"/><link rel="modulepreload" href="/assets/QueryClientProvider-BaDci0ad.js"/><link rel="modulepreload" href="/assets/confirmation-D5HO26Sg.js"/><link rel="modulepreload" href="/assets/generals-CQmk6nd9.js"/><link rel="modulepreload" href="/assets/notifications.store-DGy2UjIi.js"/><link rel="modulepreload" href="/assets/px-CiO0pVtX.js"/><link rel="modulepreload" href="/assets/get-contrast-color-Hdb80ZjZ.js"/><link rel="modulepreload" href="/assets/Flex-DcUbXdt5.js"/><link rel="modulepreload" href="/assets/ActionIcon-CQ24rhHf.js"/><link rel="modulepreload" href="/assets/Alert-CGjzIP0H.js"/><link rel="modulepreload" href="/assets/root--oQZ8YrH.js"/><script>window.__remixContext = {"url":"/backend/graphql","basename":"/","future":{"v3_fetcherPersist":false,"v3_relativeSplatPath":false,"v3_throwAbortReason":false,"unstable_singleFetch":true,"unstable_fogOfWar":false},"isSpaMode":false};window.__remixContext.stream = new ReadableStream({start(controller){window.__remixContext.streamController = controller;}}).pipeThrough(new TextEncoderStream());</script><script type="module" async="">import "/assets/manifest-49b49c4e.js";
import * as route0 from "/assets/root--oQZ8YrH.js";

window.__remixRouteModules = {"root":route0};

import("/assets/entry.client-De8lnbfs.js");</script></body></html><!--$--><script>window.__remixContext.streamController.enqueue("[{\"1\":2,\"3\":-5,\"4\":5},\"loaderData\",{},\"actionData\",\"errors\",{\"6\":7},\"root\",{\"8\":9,\"10\":11,\"12\":13,\"14\":15,\"16\":17,\"20\":21},\"status\",404,\"statusText\",\"Not Found\",\"internal\",true,\"data\",\"Error: No route matches URL \\\"/backend/graphql\\\"\",\"error\",[\"SanitizedError\",18,19,-7],\"Error\",\"Unexpected Server Error\",\"__type\",\"RouteErrorResponse\"]\n");</script><!--$--><script>window.__remixContext.streamController.close();</script><!--/$--><!--/$-->
```

By clicking on the ply button, network console reports the following:
```
Failed to load resource: the server responded with a status of 404 ()
generals-C1GAQi2t.js:96 
        
        
       POST https://ryot.anywhere.com/backend/graphql 404 (Not Found)
(anonymous) @ generals-C1GAQi2t.js:96
Lt @ generals-C1GAQi2t.js:96
request @ generals-C1GAQi2t.js:96
queryFn @ hooks-B53cwPBx.js:1
r @ generals-C1GAQi2t.js:1
j @ generals-C1GAQi2t.js:1
start @ generals-C1GAQi2t.js:1
fetch @ generals-C1GAQi2t.js:1
fetchQuery @ generals-C1GAQi2t.js:1
ensureQueryData @ generals-C1GAQi2t.js:1
(anonymous) @ media-LA8zAuRL.js:1
onClick @ _dashboard._index-DvQ-vBQL.js:16
um @ components-COXvEb0c.js:37
cm @ components-COXvEb0c.js:37
fm @ components-COXvEb0c.js:37
Gs @ components-COXvEb0c.js:37
hd @ components-COXvEb0c.js:37
(anonymous) @ components-COXvEb0c.js:37
Bu @ components-COXvEb0c.js:40
If @ components-COXvEb0c.js:37
Ui @ components-COXvEb0c.js:37
mu @ components-COXvEb0c.js:37
Rm @ components-COXvEb0c.js:37
generals-C1GAQi2t.js:96 Uncaught (in promise) Error: GraphQL Error (Code: 404): {"response":{"status":404,"headers":{}},"request":{"query":"query MetadataDetails($metadataId: String!) {\n  metadataDetails(metadataId: $metadataId) {\n    id\n    lot\n    title\n    source\n    isNsfw\n    isPartial\n    sourceUrl\n    identifier\n    description\n    publishYear\n    publishDate\n    providerRating\n    productionStatus\n    originalLanguage\n    genres {\n      id\n      name\n    }\n    group {\n      id\n      name\n      part\n    }\n    assets {\n      images\n      videos {\n        videoId\n        source\n      }\n    }\n    creators {\n      name\n      items {\n        id\n        name\n        image\n        character\n      }\n    }\n    suggestions {\n      ...PartialMetadataPart\n    }\n    watchProviders {\n      name\n      image\n      languages\n    }\n    animeSpecifics {\n      episodes\n    }\n    audioBookSpecifics {\n      runtime\n    }\n    bookSpecifics {\n      pages\n    }\n    movieSpecifics {\n      runtime\n    }\n    mangaSpecifics {\n      volumes\n      chapters\n    }\n    podcastSpecifics {\n      episodes {\n        id\n        title\n        overview\n        thumbnail\n        number\n        runtime\n        publishDate\n      }\n      totalEpisodes\n    }\n    showSpecifics {\n      totalSeasons\n      totalEpisodes\n      runtime\n      seasons {\n        id\n        seasonNumber\n        name\n        overview\n        backdropImages\n        posterImages\n        episodes {\n          id\n          name\n          posterImages\n          episodeNumber\n          publishDate\n          name\n          overview\n          runtime\n        }\n      }\n    }\n    visualNovelSpecifics {\n      length\n    }\n    videoGameSpecifics {\n      platforms\n    }\n  }\n}\n\nfragment PartialMetadataPart on PartialMetadata {\n  id\n  lot\n  source\n  identifier\n  title\n  image\n}","variables":{"metadataId":"met_Aa2Pa-2XOXE3"}}}
    at Lt (generals-C1GAQi2t.js:96:1617)
    at async Gi.request (generals-C1GAQi2t.js:96:4909)
```

**Comment by IgnisDa** [comment]
Please try to visit https://ryot.anywhere/backend/config in your browser.

**Comment by edersong** [comment]
It drives me to a page where reports the following:

![image](https://github.com/IgnisDa/ryot/assets/64137913/34defaea-9d38-48d0-bda4-0d98d697ff28)

Even logging out and logging in it still presenting the same issue

**Comment by IgnisDa** [comment]
That is very weird. Someone mentioned this in the Ryot Discord some time ago. Can you try this?

![image](https://github.com/IgnisDa/ryot/assets/60938164/47c7cd10-678c-49f4-badc-a73db6caa044)

**Comment by edersong** [comment]
It's disabled:

![image](https://github.com/IgnisDa/ryot/assets/64137913/fe3d76f1-1148-4cbc-be09-0334768f07d4)

Also, tested and it's failing also locally.

**Comment by edersong** [comment]
Enabled it but still failing:

![image](https://github.com/IgnisDa/ryot/assets/64137913/c8f7a404-648c-4e32-96d5-9061d2cb2d03)

Additionally, tested locally with the same behavior

**Comment by edersong** [comment]
Thanks for the support thru [Discord channel](https://discord.com/channels/1239445721502056459/)  @IgnisDa !!
Summarizing it, problem started on v6.3.2 onwards and we found that the root cause is that I was using port 3000 instead of 8000. Changing it to 8000, it works fine.
