### ISSUE TITLE
No route matches URL /backend/graphql

### ISSUE THREAD

**Issue by MyWay** [IgnisDa/ryot#958]
Hi, I'm on the latest version (arm image it's now working), but I'm getting the following error:

```
[frontend] Error: No route matches URL "/backend/graphql"
[frontend]     at getInternalRouterError (/home/ryot/node_modules/@remix-run/router/router.ts:5402:5)
[frontend]     at Object.query (/home/ryot/node_modules/@remix-run/router/router.ts:3511:19)
[frontend]     at handleDocumentRequest (/home/ryot/node_modules/@remix-run/server-runtime/dist/server.js:268:35)
[frontend]     at requestHandler (/home/ryot/node_modules/@remix-run/server-runtime/dist/server.js:160:24)
[frontend]     at /home/ryot/node_modules/@remix-run/express/dist/server.js:41:28
[frontend]     at processTicksAndRejections (node:internal/process/task_queues:95:5)
[frontend] ErrorResponseImpl {
[frontend]   status: 404,
[frontend]   statusText: 'Not Found',
[frontend]   internal: true,
[frontend]   data: 'Error: No route matches URL "/backend/graphql"',
[frontend]   error: Error: No route matches URL "/backend/graphql"
[frontend]       at getInternalRouterError (/home/ryot/node_modules/@remix-run/router/router.ts:5402:5)
[frontend]       at Object.query (/home/ryot/node_modules/@remix-run/router/router.ts:3511:19)
[frontend]       at handleDocumentRequest (/home/ryot/node_modules/@remix-run/server-runtime/dist/server.js:268:35)
[frontend]       at requestHandler (/home/ryot/node_modules/@remix-run/server-runtime/dist/server.js:160:24)
[frontend]       at /home/ryot/node_modules/@remix-run/express/dist/server.js:41:28
[frontend]       at processTicksAndRejections (node:internal/process/task_queues:95:5)
[frontend] }

```

**Comment by MyWay** [comment]
Found it was the same issue as https://github.com/IgnisDa/ryot/issues/896
